// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeConflict         APIErrorCode = "conflict"
	APIErrorCodeInternalError    APIErrorCode = "internal_error"
	APIErrorCodeInvalidRequest   APIErrorCode = "invalid_request"
	APIErrorCodeMethodNotAllowed APIErrorCode = "method_not_allowed"
	APIErrorCodeNotFound         APIErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeConflict:
		return true
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidRequest:
		return true
	case APIErrorCodeMethodNotAllowed:
		return true
	case APIErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PostingStatus.
const (
	Cancelled PostingStatus = "cancelled"
	Pending   PostingStatus = "pending"
	Posted    PostingStatus = "posted"
)

// Valid indicates whether the value is a known member of the PostingStatus enum.
func (e PostingStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Pending:
		return true
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for ReconciliationStatus.
const (
	Reconciled   ReconciliationStatus = "reconciled"
	Unreconciled ReconciliationStatus = "unreconciled"
)

// Valid indicates whether the value is a known member of the ReconciliationStatus enum.
func (e ReconciliationStatus) Valid() bool {
	switch e {
	case Reconciled:
		return true
	case Unreconciled:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	Manual Source = "manual"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountsParamsSort.
const (
	ListAccountsParamsSortCreatedAt ListAccountsParamsSort = "created_at"
	ListAccountsParamsSortFqn       ListAccountsParamsSort = "fqn"
	ListAccountsParamsSortUpdatedAt ListAccountsParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListAccountsParamsSort enum.
func (e ListAccountsParamsSort) Valid() bool {
	switch e {
	case ListAccountsParamsSortCreatedAt:
		return true
	case ListAccountsParamsSortFqn:
		return true
	case ListAccountsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountsParamsSortDir.
const (
	ListAccountsParamsSortDirAsc  ListAccountsParamsSortDir = "asc"
	ListAccountsParamsSortDirDesc ListAccountsParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountsParamsSortDir enum.
func (e ListAccountsParamsSortDir) Valid() bool {
	switch e {
	case ListAccountsParamsSortDirAsc:
		return true
	case ListAccountsParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListCreditLimitHistoryParamsSort.
const (
	ListCreditLimitHistoryParamsSortCreatedAt     ListCreditLimitHistoryParamsSort = "created_at"
	ListCreditLimitHistoryParamsSortEffectiveDate ListCreditLimitHistoryParamsSort = "effective_date"
)

// Valid indicates whether the value is a known member of the ListCreditLimitHistoryParamsSort enum.
func (e ListCreditLimitHistoryParamsSort) Valid() bool {
	switch e {
	case ListCreditLimitHistoryParamsSortCreatedAt:
		return true
	case ListCreditLimitHistoryParamsSortEffectiveDate:
		return true
	default:
		return false
	}
}

// Defines values for ListCreditLimitHistoryParamsSortDir.
const (
	ListCreditLimitHistoryParamsSortDirAsc  ListCreditLimitHistoryParamsSortDir = "asc"
	ListCreditLimitHistoryParamsSortDirDesc ListCreditLimitHistoryParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListCreditLimitHistoryParamsSortDir enum.
func (e ListCreditLimitHistoryParamsSortDir) Valid() bool {
	switch e {
	case ListCreditLimitHistoryParamsSortDirAsc:
		return true
	case ListCreditLimitHistoryParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListCategoriesParamsSort.
const (
	ListCategoriesParamsSortCreatedAt ListCategoriesParamsSort = "created_at"
	ListCategoriesParamsSortFqn       ListCategoriesParamsSort = "fqn"
	ListCategoriesParamsSortUpdatedAt ListCategoriesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListCategoriesParamsSort enum.
func (e ListCategoriesParamsSort) Valid() bool {
	switch e {
	case ListCategoriesParamsSortCreatedAt:
		return true
	case ListCategoriesParamsSortFqn:
		return true
	case ListCategoriesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListCategoriesParamsSortDir.
const (
	ListCategoriesParamsSortDirAsc  ListCategoriesParamsSortDir = "asc"
	ListCategoriesParamsSortDirDesc ListCategoriesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListCategoriesParamsSortDir enum.
func (e ListCategoriesParamsSortDir) Valid() bool {
	switch e {
	case ListCategoriesParamsSortDirAsc:
		return true
	case ListCategoriesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExchangeRatesParamsSort.
const (
	ListExchangeRatesParamsSortCreatedAt     ListExchangeRatesParamsSort = "created_at"
	ListExchangeRatesParamsSortCurrencyPair  ListExchangeRatesParamsSort = "currency_pair"
	ListExchangeRatesParamsSortEffectiveDate ListExchangeRatesParamsSort = "effective_date"
	ListExchangeRatesParamsSortFromCurrency  ListExchangeRatesParamsSort = "from_currency"
	ListExchangeRatesParamsSortToCurrency    ListExchangeRatesParamsSort = "to_currency"
)

// Valid indicates whether the value is a known member of the ListExchangeRatesParamsSort enum.
func (e ListExchangeRatesParamsSort) Valid() bool {
	switch e {
	case ListExchangeRatesParamsSortCreatedAt:
		return true
	case ListExchangeRatesParamsSortCurrencyPair:
		return true
	case ListExchangeRatesParamsSortEffectiveDate:
		return true
	case ListExchangeRatesParamsSortFromCurrency:
		return true
	case ListExchangeRatesParamsSortToCurrency:
		return true
	default:
		return false
	}
}

// Defines values for ListExchangeRatesParamsSortDir.
const (
	ListExchangeRatesParamsSortDirAsc  ListExchangeRatesParamsSortDir = "asc"
	ListExchangeRatesParamsSortDirDesc ListExchangeRatesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListExchangeRatesParamsSortDir enum.
func (e ListExchangeRatesParamsSortDir) Valid() bool {
	switch e {
	case ListExchangeRatesParamsSortDirAsc:
		return true
	case ListExchangeRatesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMembersParamsSort.
const (
	ListMembersParamsSortCreatedAt ListMembersParamsSort = "created_at"
	ListMembersParamsSortName      ListMembersParamsSort = "name"
	ListMembersParamsSortUpdatedAt ListMembersParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListMembersParamsSort enum.
func (e ListMembersParamsSort) Valid() bool {
	switch e {
	case ListMembersParamsSortCreatedAt:
		return true
	case ListMembersParamsSortName:
		return true
	case ListMembersParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListMembersParamsSortDir.
const (
	ListMembersParamsSortDirAsc  ListMembersParamsSortDir = "asc"
	ListMembersParamsSortDirDesc ListMembersParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListMembersParamsSortDir enum.
func (e ListMembersParamsSortDir) Valid() bool {
	switch e {
	case ListMembersParamsSortDirAsc:
		return true
	case ListMembersParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsSort.
const (
	ListTagsParamsSortCreatedAt ListTagsParamsSort = "created_at"
	ListTagsParamsSortFqn       ListTagsParamsSort = "fqn"
	ListTagsParamsSortUpdatedAt ListTagsParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListTagsParamsSort enum.
func (e ListTagsParamsSort) Valid() bool {
	switch e {
	case ListTagsParamsSortCreatedAt:
		return true
	case ListTagsParamsSortFqn:
		return true
	case ListTagsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsSortDir.
const (
	ListTagsParamsSortDirAsc  ListTagsParamsSortDir = "asc"
	ListTagsParamsSortDirDesc ListTagsParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListTagsParamsSortDir enum.
func (e ListTagsParamsSortDir) Valid() bool {
	switch e {
	case ListTagsParamsSortDirAsc:
		return true
	case ListTagsParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// Account defines model for Account.
type Account struct {
	AccountId      int64   `json:"account_id"`
	CreatedAt      string  `json:"created_at"`
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       bool    `json:"is_hidden"`
	Kind           string  `json:"kind"`
	Level          int     `json:"level"`
	Name           string  `json:"name"`
	ParentFqn      *string `json:"parent_fqn,omitempty"`
	TombstonedAt   *string `json:"tombstoned_at,omitempty"`
	UpdatedAt      string  `json:"updated_at"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Accounts []Account `json:"accounts"`
}

// BulkCategorizeRecordsRequest defines model for BulkCategorizeRecordsRequest.
type BulkCategorizeRecordsRequest struct {
	CategoryId int64   `json:"category_id"`
	RecordIds  []int64 `json:"record_ids"`
}

// BulkReassignRecordsAccountRequest defines model for BulkReassignRecordsAccountRequest.
type BulkReassignRecordsAccountRequest struct {
	AccountId int64   `json:"account_id"`
	RecordIds []int64 `json:"record_ids"`
}

// BulkRecordOperationResponse defines model for BulkRecordOperationResponse.
type BulkRecordOperationResponse struct {
	RecordIds    []int64 `json:"record_ids"`
	UpdatedCount int     `json:"updated_count"`
}

// BulkTagRecordsRequest Provide at least one non-empty add_tag_ids or remove_tag_ids array. The two arrays must not overlap.
type BulkTagRecordsRequest struct {
	AddTagIds    *[]int64 `json:"add_tag_ids,omitempty"`
	RecordIds    []int64  `json:"record_ids"`
	RemoveTagIds *[]int64 `json:"remove_tag_ids,omitempty"`
}

// BulkUpdateRecordStatusRequest Provide posting_status, reconciliation_status, or both.
type BulkUpdateRecordStatusRequest struct {
	PostingStatus        *PostingStatus        `json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `json:"reconciliation_status,omitempty"`
	RecordIds            []int64               `json:"record_ids"`
}

// Category defines model for Category.
type Category struct {
	CategoryId   int64   `json:"category_id"`
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Categories []Category `json:"categories"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       *bool   `json:"is_hidden,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreateCreditLimitHistoryRequest defines model for CreateCreditLimitHistoryRequest.
type CreateCreditLimitHistoryRequest struct {
	CreditLimit   string `json:"credit_limit"`
	EffectiveDate string `json:"effective_date"`
}

// CreateExchangeRateRequest defines model for CreateExchangeRateRequest.
type CreateExchangeRateRequest struct {
	EffectiveDate string `json:"effective_date"`
	FromCurrency  string `json:"from_currency"`
	Rate          string `json:"rate"`
	ToCurrency    string `json:"to_currency"`
}

// CreateJournalRecordRequest defines model for CreateJournalRecordRequest.
type CreateJournalRecordRequest struct {
	AccountId            int64                `json:"account_id"`
	Amount               string               `json:"amount"`
	AmountUsd            string               `json:"amount_usd"`
	CategoryId           int64                `json:"category_id"`
	Currency             string               `json:"currency"`
	ExternalId           *string              `json:"external_id,omitempty"`
	ExternalSystem       *string              `json:"external_system,omitempty"`
	MemberId             *int64               `json:"member_id,omitempty"`
	Memo                 *string              `json:"memo,omitempty"`
	PendingDate          *string              `json:"pending_date,omitempty"`
	PostedDate           *string              `json:"posted_date,omitempty"`
	PostingStatus        PostingStatus        `json:"posting_status"`
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	Source               Source               `json:"source"`
	TagIds               *[]int64             `json:"tag_ids,omitempty"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	Name string `json:"name"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	InitiatedDate string                       `json:"initiated_date"`
	Records       []CreateJournalRecordRequest `json:"records"`
}

// CreditLimitHistory defines model for CreditLimitHistory.
type CreditLimitHistory struct {
	AccountId            int64   `json:"account_id"`
	CreatedAt            string  `json:"created_at"`
	CreditLimit          string  `json:"credit_limit"`
	CreditLimitHistoryId int64   `json:"credit_limit_history_id"`
	EffectiveDate        string  `json:"effective_date"`
	TombstonedAt         *string `json:"tombstoned_at,omitempty"`
}

// CreditLimitHistoryListResponse defines model for CreditLimitHistoryListResponse.
type CreditLimitHistoryListResponse struct {
	CreditLimitHistory []CreditLimitHistory `json:"credit_limit_history"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// ExchangeRate defines model for ExchangeRate.
type ExchangeRate struct {
	CreatedAt      string  `json:"created_at"`
	EffectiveDate  string  `json:"effective_date"`
	ExchangeRateId int64   `json:"exchange_rate_id"`
	FromCurrency   string  `json:"from_currency"`
	Rate           string  `json:"rate"`
	ToCurrency     string  `json:"to_currency"`
	TombstonedAt   *string `json:"tombstoned_at,omitempty"`
}

// ExchangeRateListResponse defines model for ExchangeRateListResponse.
type ExchangeRateListResponse struct {
	ExchangeRates []ExchangeRate `json:"exchange_rates"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JournalRecord defines model for JournalRecord.
type JournalRecord struct {
	AccountId            int64                `json:"account_id"`
	Amount               string               `json:"amount"`
	AmountUsd            string               `json:"amount_usd"`
	CategoryId           int64                `json:"category_id"`
	CreatedAt            string               `json:"created_at"`
	Currency             string               `json:"currency"`
	ExternalId           *string              `json:"external_id,omitempty"`
	ExternalSystem       *string              `json:"external_system,omitempty"`
	MemberId             *int64               `json:"member_id,omitempty"`
	Memo                 *string              `json:"memo,omitempty"`
	PendingDate          *string              `json:"pending_date,omitempty"`
	PostedDate           *string              `json:"posted_date,omitempty"`
	PostingStatus        PostingStatus        `json:"posting_status"`
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	RecordId             int64                `json:"record_id"`
	Source               Source               `json:"source"`
	TagIds               []int64              `json:"tag_ids"`
	TombstonedAt         *string              `json:"tombstoned_at,omitempty"`
	TransactionId        int64                `json:"transaction_id"`
	UpdatedAt            string               `json:"updated_at"`
}

// JournalRecordSearchResponse defines model for JournalRecordSearchResponse.
type JournalRecordSearchResponse struct {
	Records []JournalRecord `json:"records"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt    string  `json:"created_at"`
	MemberId     int64   `json:"member_id"`
	Name         string  `json:"name"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// MemberListResponse defines model for MemberListResponse.
type MemberListResponse struct {
	Members []Member `json:"members"`
}

// PostingStatus defines model for PostingStatus.
type PostingStatus string

// ReconciliationStatus defines model for ReconciliationStatus.
type ReconciliationStatus string

// Source defines model for Source.
type Source string

// Tag defines model for Tag.
type Tag struct {
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TagId        int64   `json:"tag_id"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// TagListResponse defines model for TagListResponse.
type TagListResponse struct {
	Tags []Tag `json:"tags"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	CreatedAt     string          `json:"created_at"`
	InitiatedDate string          `json:"initiated_date"`
	Records       []JournalRecord `json:"records"`
	TombstonedAt  *string         `json:"tombstoned_at,omitempty"`
	TransactionId int64           `json:"transaction_id"`
}

// TransactionListResponse defines model for TransactionListResponse.
type TransactionListResponse struct {
	Transactions []Transaction `json:"transactions"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	IsHidden       bool    `json:"is_hidden"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// UpdateExchangeRateRequest defines model for UpdateExchangeRateRequest.
type UpdateExchangeRateRequest struct {
	Rate string `json:"rate"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Name string `json:"name"`
}

// UpdateTagRequest defines model for UpdateTagRequest.
type UpdateTagRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// UpdateTransactionRequest defines model for UpdateTransactionRequest.
type UpdateTransactionRequest struct {
	InitiatedDate string                       `json:"initiated_date"`
	Records       []CreateJournalRecordRequest `json:"records"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	IncludeHidden     *bool                      `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                      `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListAccountsParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListAccountsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                       `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAccountsParamsSort defines parameters for ListAccounts.
type ListAccountsParamsSort string

// ListAccountsParamsSortDir defines parameters for ListAccounts.
type ListAccountsParamsSortDir string

// GetAccountParams defines parameters for GetAccount.
type GetAccountParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListCreditLimitHistoryParams defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParams struct {
	IncludeTombstoned *bool                                `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListCreditLimitHistoryParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListCreditLimitHistoryParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCreditLimitHistoryParamsSort defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParamsSort string

// ListCreditLimitHistoryParamsSortDir defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParamsSortDir string

// SearchAccountJournalRecordsParams defines parameters for SearchAccountJournalRecords.
type SearchAccountJournalRecordsParams struct {
	CategoryId           *int64                `form:"category_id,omitempty" json:"category_id,omitempty"`
	TagId                *int64                `form:"tag_id,omitempty" json:"tag_id,omitempty"`
	MemberId             *int64                `form:"member_id,omitempty" json:"member_id,omitempty"`
	PostingStatus        *PostingStatus        `form:"posting_status,omitempty" json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	AmountMin            *string               `form:"amount_min,omitempty" json:"amount_min,omitempty"`
	AmountMax            *string               `form:"amount_max,omitempty" json:"amount_max,omitempty"`
	AmountUsdMin         *string               `form:"amount_usd_min,omitempty" json:"amount_usd_min,omitempty"`
	AmountUsdMax         *string               `form:"amount_usd_max,omitempty" json:"amount_usd_max,omitempty"`
	InitiatedDateFrom    *string               `form:"initiated_date_from,omitempty" json:"initiated_date_from,omitempty"`
	InitiatedDateTo      *string               `form:"initiated_date_to,omitempty" json:"initiated_date_to,omitempty"`
	PendingDateFrom      *string               `form:"pending_date_from,omitempty" json:"pending_date_from,omitempty"`
	PendingDateTo        *string               `form:"pending_date_to,omitempty" json:"pending_date_to,omitempty"`
	PostedDateFrom       *string               `form:"posted_date_from,omitempty" json:"posted_date_from,omitempty"`
	PostedDateTo         *string               `form:"posted_date_to,omitempty" json:"posted_date_to,omitempty"`
	MemoContains         *string               `form:"memo_contains,omitempty" json:"memo_contains,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	IncludeHidden     *bool                        `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                        `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListCategoriesParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListCategoriesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                         `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCategoriesParamsSort defines parameters for ListCategories.
type ListCategoriesParamsSort string

// ListCategoriesParamsSortDir defines parameters for ListCategories.
type ListCategoriesParamsSortDir string

// GetCategoryParams defines parameters for GetCategory.
type GetCategoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetCreditLimitHistoryParams defines parameters for GetCreditLimitHistory.
type GetCreditLimitHistoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListExchangeRatesParams defines parameters for ListExchangeRates.
type ListExchangeRatesParams struct {
	FromCurrency      *string                         `form:"from_currency,omitempty" json:"from_currency,omitempty"`
	ToCurrency        *string                         `form:"to_currency,omitempty" json:"to_currency,omitempty"`
	EffectiveDate     *string                         `form:"effective_date,omitempty" json:"effective_date,omitempty"`
	IncludeTombstoned *bool                           `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListExchangeRatesParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListExchangeRatesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                            `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExchangeRatesParamsSort defines parameters for ListExchangeRates.
type ListExchangeRatesParamsSort string

// ListExchangeRatesParamsSortDir defines parameters for ListExchangeRates.
type ListExchangeRatesParamsSortDir string

// GetExchangeRateParams defines parameters for GetExchangeRate.
type GetExchangeRateParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	IncludeTombstoned *bool                     `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListMembersParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListMembersParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                      `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMembersParamsSort defines parameters for ListMembers.
type ListMembersParamsSort string

// ListMembersParamsSortDir defines parameters for ListMembers.
type ListMembersParamsSortDir string

// GetMemberParams defines parameters for GetMember.
type GetMemberParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// SearchJournalRecordsParams defines parameters for SearchJournalRecords.
type SearchJournalRecordsParams struct {
	AccountId            *int64                `form:"account_id,omitempty" json:"account_id,omitempty"`
	CategoryId           *int64                `form:"category_id,omitempty" json:"category_id,omitempty"`
	TagId                *int64                `form:"tag_id,omitempty" json:"tag_id,omitempty"`
	MemberId             *int64                `form:"member_id,omitempty" json:"member_id,omitempty"`
	PostingStatus        *PostingStatus        `form:"posting_status,omitempty" json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	AmountMin            *string               `form:"amount_min,omitempty" json:"amount_min,omitempty"`
	AmountMax            *string               `form:"amount_max,omitempty" json:"amount_max,omitempty"`
	AmountUsdMin         *string               `form:"amount_usd_min,omitempty" json:"amount_usd_min,omitempty"`
	AmountUsdMax         *string               `form:"amount_usd_max,omitempty" json:"amount_usd_max,omitempty"`
	InitiatedDateFrom    *string               `form:"initiated_date_from,omitempty" json:"initiated_date_from,omitempty"`
	InitiatedDateTo      *string               `form:"initiated_date_to,omitempty" json:"initiated_date_to,omitempty"`
	PendingDateFrom      *string               `form:"pending_date_from,omitempty" json:"pending_date_from,omitempty"`
	PendingDateTo        *string               `form:"pending_date_to,omitempty" json:"pending_date_to,omitempty"`
	PostedDateFrom       *string               `form:"posted_date_from,omitempty" json:"posted_date_from,omitempty"`
	PostedDateTo         *string               `form:"posted_date_to,omitempty" json:"posted_date_to,omitempty"`
	MemoContains         *string               `form:"memo_contains,omitempty" json:"memo_contains,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	IncludeHidden     *bool                  `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                  `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListTagsParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListTagsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                   `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTagsParamsSort defines parameters for ListTags.
type ListTagsParamsSort string

// ListTagsParamsSortDir defines parameters for ListTags.
type ListTagsParamsSortDir string

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreateCreditLimitHistoryJSONRequestBody defines body for CreateCreditLimitHistory for application/json ContentType.
type CreateCreditLimitHistoryJSONRequestBody = CreateCreditLimitHistoryRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CreateExchangeRateJSONRequestBody defines body for CreateExchangeRate for application/json ContentType.
type CreateExchangeRateJSONRequestBody = CreateExchangeRateRequest

// UpdateExchangeRateJSONRequestBody defines body for UpdateExchangeRate for application/json ContentType.
type UpdateExchangeRateJSONRequestBody = UpdateExchangeRateRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// BulkReassignJournalRecordAccountJSONRequestBody defines body for BulkReassignJournalRecordAccount for application/json ContentType.
type BulkReassignJournalRecordAccountJSONRequestBody = BulkReassignRecordsAccountRequest

// BulkCategorizeJournalRecordsJSONRequestBody defines body for BulkCategorizeJournalRecords for application/json ContentType.
type BulkCategorizeJournalRecordsJSONRequestBody = BulkCategorizeRecordsRequest

// BulkUpdateJournalRecordStatusesJSONRequestBody defines body for BulkUpdateJournalRecordStatuses for application/json ContentType.
type BulkUpdateJournalRecordStatusesJSONRequestBody = BulkUpdateRecordStatusRequest

// BulkUpdateJournalRecordTagsJSONRequestBody defines body for BulkUpdateJournalRecordTags for application/json ContentType.
type BulkUpdateJournalRecordTagsJSONRequestBody = BulkTagRecordsRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// ReplaceTransactionJSONRequestBody defines body for ReplaceTransaction for application/json ContentType.
type ReplaceTransactionJSONRequestBody = UpdateTransactionRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1bc+O2Ff4rGDYP7Yxs2ZtNp/FLxklz2U423Xrdl262GpiEJGRJQguA3lU8+u8dAAQJUAAvEknRqZ4s",
	"2yRw7vgOzgH0FIQk2ZAUpZwFN08BRWxDUobkL9+RdBnjkIvPIUk5SuVHuNnEOIQck3T+GyOp+BsL1yiB",
	"4tMXFC2Dm+BP83Lgufovm39PKaF3+RTBbrebBRFiIcUbMVhwE9yvEaDoY4YYB2E+OwOfMF8D9BkzjtMV",
	"YBxydBnsZsGr9BHGOLpTL5yGSswAVmRIkl4jvibRL4TfxjH5hKKRiSIZRyAiiIGUcMCyzYZQDnhJL4pA",
	"IkmU1P5C+A8kS6OTiA5FgCJGMhoi8AkqipeCmstAvJcPKWa8ffNKDixpiyIsxoLxG0o2iHIsbHUJY4Zm",
	"wcb4k+AoQuInSrMkuHkX5Hpa5PMHsyAlfCGnDGaBEstC/AnmupsF2gaDWYBTjmgK4wWSpLyfBXy7QcFN",
	"wDjF6UqIM0GMwZWcs/K/3SwQs2IqLOKdoqx8vhyLPPyGQi7Gug1DkuXqaM8yVG8tsFTpktAE8uBG0P7X",
	"l0Exi2BlhaiYJqQIchQtIHdQPQvCjFKUhlvxzzSLY/gQo+CG00zMDLmQSHAT/Pfd7cV/3j99ufsicEgF",
	"fc4Fp4iqDuN/nm0ZR0mrd5YfUyf9mC3WOIqQ+d8HQmIEU/HvD1jZ/t57MXpEsfEfQ2IpTJDznQ2kKOWL",
	"nJRGkjlJHhgnaSH8xjeyTeTXVcXCDENQ0smZNUWS86K5tYzBmq3GPn/GjBf+fpCtys+Yo4Q1BRftEruC",
	"HEgp3Pp4Z066v83iD99BjlaE4t/RHQoJjZixgnSJL2qYrc/bEpziRISea5fnUTn1Ake2ADqOkuD0lXr1",
	"uiKVWZCl+GOG8n8Lm6oKyiBhZnHjE9wdgozhVZqLLVfIYdJrCFXPS3gGM37Zief/uUFULqwHOk1bxveZ",
	"tV2m9O9imSlkdbX/eh3v9kA+9u/hqqOz2cDhDSWPOEIAchAjyDggKQIpSS9QsuFbAKNoweFKkAQIBRQl",
	"5BEVf5FMXwIBPvgnon5lIMkYl6iDPCIaw82lMhiTlBd7VlvOM57lncbexaymFKfgaT7r+re0QWVgbznk",
	"2ZFWtiEy11gwOdYMCBLSEMdY+m7xZ0LBA+HrNoZjj9i01L1RTytWdMDbI6BplDvrJXuw6URPl07zFXrb",
	"84rcGf8eiCufPXw0BanxY0/AUav2COSYU5f/1go7FgbVBB6NsZ3US06PAj5/qJwqQkuYxbxgteoLFemK",
	"Mf1i1Uo6TK4noJeiCPOfcYL5T5jxgykP5TiLWAwkkRj8/DNKV3wd3Fx/bRvF1cXX75+uZ9dXuz//+uul",
	"/vVvu79847aT5RKFHD+ihfBJuQ5VB3u5u1AfXpQfHGNV3cQkeW8ev8i+/xyuYbpCd3K5PkRY/bE0C5aU",
	"JAvTH9v6H82nrmgqJbwyylWprKtCUbujdMrJASRX7dpi3B4z566DUv9BMhFcFPw6QTYIkyKHKfXx4sqS",
	"8sU3XeWsRl1kLOp75OM2Dg6x1zHWiwQlD4i24ckzlIktUUJaTbpBaSRgtY4FdQtqt9ggADuKBhp4KpmA",
	"2n5vevutekrEnuNTwTZbdwp2GhEp93DLKWcVlFqRq09SBdP+ePZaWvJhgcyD7yt8yqf8BMjNkueBge4p",
	"TBkM1ZbWISTjFHMMTVc73LVUVtkhK/AvX1aC+6LBbCs8lIR45FZBjacu8gwGP82RF2vFbHuy+0R6XdPl",
	"GrhrMjKrRKxaVGwpop1lHJMkO0ju4hhVG21MnF3zubi0a8Qdwb8uA9fWiXS5uEpitXJr0GSkJd3lXOdc",
	"fRoxyqlcCIDe3o/+f7Kco/18T8Kzg1KlRk837e0IH7fIbb/sWdbe5NeVOVzc/IRgzNcH8lACWN2nQT44",
	"uisqVOVvuaixlvOhl9Y/Wup5VIfI88lGzxno5GpRLc1xkIy1uVrevdzCy8SoPXddajSl5PYmmx2VSGuR",
	"dU+pu1WCrED9FkEaro/qimi/ANpLRNMKWJfMqa2CfiFjfejqUFIctkZYklnUA7toX0nuCPCj5m+v9FxV",
	"TdrWw7potkOhAVnyRSDQQVv6VBqiOEaRs1XUGQ6NAbWjyaGy1PjVNdrbIijq9xOYZjB2PnwPV/3a64SL",
	"5DKStQ35g3pLTkrPxfR7uDrCgzhctXcfYTZNviMHdNJZrk/92t4pdw8bVpGRQENVBVUksLc3adlX3dpm",
	"KO0YIytH6WBshr00Gp05gYsP1Rx2VM/GGBlLbbisbjgXz/oZPq6bom9qji/8n243qooHfdVwxekJq0eK",
	"gIOrR33r/Fwb6lYb2skFbSn3HTjmIlYEr3EKwd33b+/B7ZtXwSx4RJSpXtWry+vLK0EL2aAUbnBwE3x5",
	"eXX5ZSAtfS0ZnJuHLFZIyp/oFvRXUXATiMh+qx+SAAsmiEtc/U4oILgJPmaIbjVOEStPGGcRKvFLeTSs",
	"ubJYP2S5YPYyLCOUuwfKUZhGy+q3ZuBV+qN/wkWEqWdSyEJjUvVbhFjYYQZdWiqHT+BnVW3/6uqqvvbu",
	"G5MslwxVBq07C/B+Zh8TfXF11dsBQtexIscxQm2xAKcgEuYqCGYch+CHf/0CCI0QlQccXyrSXDMWLMwr",
	"x0jl4cMsSSDd5v4BtBdd6t2zfT+yGkMDFQIQ49+SaNubcJzNpzs74BSt+5aCrvtWUI1SQO5HhytAvPZ1",
	"82vF8WRbY0pKAKZabeo8aREK50/l5thOOWiM1Opiq/Tv8u+mSi2ZvlTvuiRQxrHjhPCy+bXiCK8thHtN",
	"gS2HmXsR+BHxks0OS8Ch8XqECFJnoPqU8Uk08yPiVZ24JC6W8FLg1nau7eym4Du1YgktbCAP1/v2YGVM",
	"AwUzZ1bWKpiNais5DjiVtSgpaWsBCnOpKxAATCOgE02AI5RyvMSIsrp4N1dtGhcSR1wYbSFecOhoBRkl",
	"RnTHdHtFeI202lXnz+BuaHDX0N/k8EL1BpCCAbm1CsxXaPRCuseRgO84F5UIMXQRuiR0QqG+BrY6fXw4",
	"BOs/NzMymHW1ubU0QpRyuu0H6nYyvX6wsdteJU+1q4exieJcMFQVN187rb2TlpsLdiX6UHP3xMKiBtPz",
	"uGYltOeh9yrw7Qy70rPhG91bzm81ibulwzdX3nCQ4LS6wvXU3NQ0Mfx8mokzFp2Oazn56Jzbe56LJSWJ",
	"RcHhhxBbzcfJoLOZHV/D82bNNjRnZcfZCIwZkw3MV4ISshCIAeLUjm/VAYaEv3X9Tg7Y8Vrk5jhdASiR",
	"bpED5muwuhUvZ0o8ZtRB82yQb3vaBFXEakJ+U3wUhAiYK3eaJoBzBXSxrwfwJ7blY+e6x7nuceLU2HUr",
	"hisXKYx2pNJH6UyNxY/ijo1Bc8dKV8PYGWNxj4hXN9upFEC07nRKV6py/mTkWS1qIJZmm4oghRgmVQUx",
	"heGvghiMPvMySCtDPX0hxFZLM2qw9wfGqoQMHNnc/Voj10JaGcw0qiHaCKxyiA5yjvrG/MlzfrdN6HNv",
	"jTYGQf+e4cTCYt1GYE2gPFFVaNzyRMfd4CmE03p1tgiw3pPuveZo+lTpRXFy1ZunmZ2jLVO16pld985C",
	"3W1Jng1kMsSoe+XJITfKxk44tbwWGyjzQ50FVv9ef8z6XMGdRprqPbfuCJT6WSBdfD9d1eqd91HC3U9c",
	"kTV9Y/JqnYkfMoF1NcKPnMTa5/8bNDeddj5Lozncs9eR+VP1AocWCG9P803YzhbPxHr9qkLyQ7gK388c",
	"vHWz6Sl0AO5rqhmdOe4nGSsHHiFA+k8KjZwLdzOmibQIViwKPMI402FyLW9o8cLsHxFXd7gEAwq1ckuM",
	"58uBNpSEiDGAGYCPEMsjc7lkv2oW0d7XL9miukPy+5D0HEoquYiM4+TeVOR1/sxEGyDzg8QawbY+lH/G",
	"zUPjZsdlB66KrzKvfagsOOofIa9JxtCaxBHIbb8RJOdXKAwJj+3TkyMDY31FhE81k6nsVFVnx7D5U9GR",
	"1gL/GkptQr65FKa1g+mQhR/0Fsw+c7jbaKkT2It0KqYZ45rdlGOB20EDm+tY+MiAttFcxsewx0XCHPRW",
	"TUyulHkwbNerfEiTstW61HPD77kB+twAfW6APjdAnxugzw3Q5wZoqwG62neMU6vnufcyUm3Xsw0y5g9Z",
	"/EGfmdJf97cPOczvULWEMexR6+avbh0ZjtZ9H6rDENSjxS0cgOa8HINXLU3fyuHMJnbACWAoRiFHURvV",
	"h8YXFvp1X37x8B7sHErv3u86fg4qZ0X78e9D6DosO1U7Kbu88divapWg2BFPvoaG1Lb/e1CfhYezXELH",
	"p6OuZDFPJeS9CTbwLycWnztYgr5Bs5Md3IuXhrOB/W9afha6F6LsWe+3UZQrOyGPSM3QrGCtU28VKNff",
	"+cjQuaZ0yppS9e5fV0FVWPw454SE1zTWj+7hatDikXHz5ciVI3k7slMBk6kZcbgyItz8SW0GtigQaa01",
	"VYcEs9MqDSmW/dUgxdkzLwXVmN4EikBaBc11n2Jzeqyiz3DRaO8e3pERWI1JTKNZicOV6/BO9a5wPwQz",
	"HxxSkJ4r0F3CNUgSa26xJWtfUeVYOc0X5aH+fVzasKwat6UPurzu3+c89jJr3gtfq4Pjl133KvoAY5iG",
	"KDLV5rDe+ZN9EX+bZbaixcbl1mB2YsuuQZnIvzBnTpv2Lst1krg6hTFNYSE1yPFHieZVtvr9EH2uthnf",
	"N9M7tIlhKA+AmDUqaRh8jcAyi+MKL4AJjjlJcAjjeHsJ7tcI2IQDzMCGIoboI4pm4uMjJhnTm/W6RACp",
	"2aA/y3cDJEEJMu5SSTLGtWsDTsDviBJQVhAvg1nFSnOuho+83pv0x4YU7Z0lF/DJ/CXXTetAtNvt/hcA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
