// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeConflict         APIErrorCode = "conflict"
	APIErrorCodeInternalError    APIErrorCode = "internal_error"
	APIErrorCodeInvalidRequest   APIErrorCode = "invalid_request"
	APIErrorCodeMethodNotAllowed APIErrorCode = "method_not_allowed"
	APIErrorCodeNotFound         APIErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeConflict:
		return true
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidRequest:
		return true
	case APIErrorCodeMethodNotAllowed:
		return true
	case APIErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PostingStatus.
const (
	Cancelled PostingStatus = "cancelled"
	Pending   PostingStatus = "pending"
	Posted    PostingStatus = "posted"
)

// Valid indicates whether the value is a known member of the PostingStatus enum.
func (e PostingStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Pending:
		return true
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for ReconciliationStatus.
const (
	Reconciled   ReconciliationStatus = "reconciled"
	Unreconciled ReconciliationStatus = "unreconciled"
)

// Valid indicates whether the value is a known member of the ReconciliationStatus enum.
func (e ReconciliationStatus) Valid() bool {
	switch e {
	case Reconciled:
		return true
	case Unreconciled:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	Manual Source = "manual"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountsParamsSort.
const (
	ListAccountsParamsSortCreatedAt ListAccountsParamsSort = "created_at"
	ListAccountsParamsSortFqn       ListAccountsParamsSort = "fqn"
	ListAccountsParamsSortUpdatedAt ListAccountsParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListAccountsParamsSort enum.
func (e ListAccountsParamsSort) Valid() bool {
	switch e {
	case ListAccountsParamsSortCreatedAt:
		return true
	case ListAccountsParamsSortFqn:
		return true
	case ListAccountsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountsParamsSortDir.
const (
	ListAccountsParamsSortDirAsc  ListAccountsParamsSortDir = "asc"
	ListAccountsParamsSortDirDesc ListAccountsParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountsParamsSortDir enum.
func (e ListAccountsParamsSortDir) Valid() bool {
	switch e {
	case ListAccountsParamsSortDirAsc:
		return true
	case ListAccountsParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListCreditLimitHistoryParamsSort.
const (
	ListCreditLimitHistoryParamsSortCreatedAt     ListCreditLimitHistoryParamsSort = "created_at"
	ListCreditLimitHistoryParamsSortEffectiveDate ListCreditLimitHistoryParamsSort = "effective_date"
)

// Valid indicates whether the value is a known member of the ListCreditLimitHistoryParamsSort enum.
func (e ListCreditLimitHistoryParamsSort) Valid() bool {
	switch e {
	case ListCreditLimitHistoryParamsSortCreatedAt:
		return true
	case ListCreditLimitHistoryParamsSortEffectiveDate:
		return true
	default:
		return false
	}
}

// Defines values for ListCreditLimitHistoryParamsSortDir.
const (
	ListCreditLimitHistoryParamsSortDirAsc  ListCreditLimitHistoryParamsSortDir = "asc"
	ListCreditLimitHistoryParamsSortDirDesc ListCreditLimitHistoryParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListCreditLimitHistoryParamsSortDir enum.
func (e ListCreditLimitHistoryParamsSortDir) Valid() bool {
	switch e {
	case ListCreditLimitHistoryParamsSortDirAsc:
		return true
	case ListCreditLimitHistoryParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListCategoriesParamsSort.
const (
	ListCategoriesParamsSortCreatedAt ListCategoriesParamsSort = "created_at"
	ListCategoriesParamsSortFqn       ListCategoriesParamsSort = "fqn"
	ListCategoriesParamsSortUpdatedAt ListCategoriesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListCategoriesParamsSort enum.
func (e ListCategoriesParamsSort) Valid() bool {
	switch e {
	case ListCategoriesParamsSortCreatedAt:
		return true
	case ListCategoriesParamsSortFqn:
		return true
	case ListCategoriesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListCategoriesParamsSortDir.
const (
	ListCategoriesParamsSortDirAsc  ListCategoriesParamsSortDir = "asc"
	ListCategoriesParamsSortDirDesc ListCategoriesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListCategoriesParamsSortDir enum.
func (e ListCategoriesParamsSortDir) Valid() bool {
	switch e {
	case ListCategoriesParamsSortDirAsc:
		return true
	case ListCategoriesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExchangeRatesParamsSort.
const (
	ListExchangeRatesParamsSortCreatedAt     ListExchangeRatesParamsSort = "created_at"
	ListExchangeRatesParamsSortCurrencyPair  ListExchangeRatesParamsSort = "currency_pair"
	ListExchangeRatesParamsSortEffectiveDate ListExchangeRatesParamsSort = "effective_date"
	ListExchangeRatesParamsSortFromCurrency  ListExchangeRatesParamsSort = "from_currency"
	ListExchangeRatesParamsSortToCurrency    ListExchangeRatesParamsSort = "to_currency"
)

// Valid indicates whether the value is a known member of the ListExchangeRatesParamsSort enum.
func (e ListExchangeRatesParamsSort) Valid() bool {
	switch e {
	case ListExchangeRatesParamsSortCreatedAt:
		return true
	case ListExchangeRatesParamsSortCurrencyPair:
		return true
	case ListExchangeRatesParamsSortEffectiveDate:
		return true
	case ListExchangeRatesParamsSortFromCurrency:
		return true
	case ListExchangeRatesParamsSortToCurrency:
		return true
	default:
		return false
	}
}

// Defines values for ListExchangeRatesParamsSortDir.
const (
	ListExchangeRatesParamsSortDirAsc  ListExchangeRatesParamsSortDir = "asc"
	ListExchangeRatesParamsSortDirDesc ListExchangeRatesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListExchangeRatesParamsSortDir enum.
func (e ListExchangeRatesParamsSortDir) Valid() bool {
	switch e {
	case ListExchangeRatesParamsSortDirAsc:
		return true
	case ListExchangeRatesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMembersParamsSort.
const (
	ListMembersParamsSortCreatedAt ListMembersParamsSort = "created_at"
	ListMembersParamsSortName      ListMembersParamsSort = "name"
	ListMembersParamsSortUpdatedAt ListMembersParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListMembersParamsSort enum.
func (e ListMembersParamsSort) Valid() bool {
	switch e {
	case ListMembersParamsSortCreatedAt:
		return true
	case ListMembersParamsSortName:
		return true
	case ListMembersParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListMembersParamsSortDir.
const (
	ListMembersParamsSortDirAsc  ListMembersParamsSortDir = "asc"
	ListMembersParamsSortDirDesc ListMembersParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListMembersParamsSortDir enum.
func (e ListMembersParamsSortDir) Valid() bool {
	switch e {
	case ListMembersParamsSortDirAsc:
		return true
	case ListMembersParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsSort.
const (
	ListTagsParamsSortCreatedAt ListTagsParamsSort = "created_at"
	ListTagsParamsSortFqn       ListTagsParamsSort = "fqn"
	ListTagsParamsSortUpdatedAt ListTagsParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListTagsParamsSort enum.
func (e ListTagsParamsSort) Valid() bool {
	switch e {
	case ListTagsParamsSortCreatedAt:
		return true
	case ListTagsParamsSortFqn:
		return true
	case ListTagsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsSortDir.
const (
	ListTagsParamsSortDirAsc  ListTagsParamsSortDir = "asc"
	ListTagsParamsSortDirDesc ListTagsParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListTagsParamsSortDir enum.
func (e ListTagsParamsSortDir) Valid() bool {
	switch e {
	case ListTagsParamsSortDirAsc:
		return true
	case ListTagsParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// Account defines model for Account.
type Account struct {
	AccountId      int64   `json:"account_id"`
	CreatedAt      string  `json:"created_at"`
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       bool    `json:"is_hidden"`
	Kind           string  `json:"kind"`
	Level          int     `json:"level"`
	Name           string  `json:"name"`
	ParentFqn      *string `json:"parent_fqn,omitempty"`
	TombstonedAt   *string `json:"tombstoned_at,omitempty"`
	UpdatedAt      string  `json:"updated_at"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Accounts []Account `json:"accounts"`
}

// BulkCategorizeRecordsRequest defines model for BulkCategorizeRecordsRequest.
type BulkCategorizeRecordsRequest struct {
	CategoryId int64   `json:"category_id"`
	RecordIds  []int64 `json:"record_ids"`
}

// BulkReassignRecordsAccountRequest defines model for BulkReassignRecordsAccountRequest.
type BulkReassignRecordsAccountRequest struct {
	AccountId int64   `json:"account_id"`
	RecordIds []int64 `json:"record_ids"`
}

// BulkRecordOperationResponse defines model for BulkRecordOperationResponse.
type BulkRecordOperationResponse struct {
	RecordIds    []int64 `json:"record_ids"`
	UpdatedCount int     `json:"updated_count"`
}

// BulkTagRecordsRequest Provide at least one non-empty add_tag_ids or remove_tag_ids array. The two arrays must not overlap.
type BulkTagRecordsRequest struct {
	AddTagIds    *[]int64 `json:"add_tag_ids,omitempty"`
	RecordIds    []int64  `json:"record_ids"`
	RemoveTagIds *[]int64 `json:"remove_tag_ids,omitempty"`
}

// BulkUpdateRecordStatusRequest Provide posting_status, reconciliation_status, or both.
type BulkUpdateRecordStatusRequest struct {
	PostingStatus        *PostingStatus        `json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `json:"reconciliation_status,omitempty"`
	RecordIds            []int64               `json:"record_ids"`
}

// Category defines model for Category.
type Category struct {
	CategoryId   int64   `json:"category_id"`
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Categories []Category `json:"categories"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       *bool   `json:"is_hidden,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreateCreditLimitHistoryRequest defines model for CreateCreditLimitHistoryRequest.
type CreateCreditLimitHistoryRequest struct {
	CreditLimit   string `json:"credit_limit"`
	EffectiveDate string `json:"effective_date"`
}

// CreateExchangeRateRequest defines model for CreateExchangeRateRequest.
type CreateExchangeRateRequest struct {
	EffectiveDate string `json:"effective_date"`
	FromCurrency  string `json:"from_currency"`
	Rate          string `json:"rate"`
	ToCurrency    string `json:"to_currency"`
}

// CreateJournalRecordRequest defines model for CreateJournalRecordRequest.
type CreateJournalRecordRequest struct {
	AccountId            int64                `json:"account_id"`
	Amount               string               `json:"amount"`
	AmountUsd            string               `json:"amount_usd"`
	CategoryId           int64                `json:"category_id"`
	Currency             string               `json:"currency"`
	ExternalId           *string              `json:"external_id,omitempty"`
	ExternalSystem       *string              `json:"external_system,omitempty"`
	MemberId             *int64               `json:"member_id,omitempty"`
	Memo                 *string              `json:"memo,omitempty"`
	PendingDate          *string              `json:"pending_date,omitempty"`
	PostedDate           *string              `json:"posted_date,omitempty"`
	PostingStatus        PostingStatus        `json:"posting_status"`
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	Source               Source               `json:"source"`
	TagIds               *[]int64             `json:"tag_ids,omitempty"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	Name string `json:"name"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	InitiatedDate string                       `json:"initiated_date"`
	Records       []CreateJournalRecordRequest `json:"records"`
}

// CreditLimitHistory defines model for CreditLimitHistory.
type CreditLimitHistory struct {
	AccountId            int64   `json:"account_id"`
	CreatedAt            string  `json:"created_at"`
	CreditLimit          string  `json:"credit_limit"`
	CreditLimitHistoryId int64   `json:"credit_limit_history_id"`
	EffectiveDate        string  `json:"effective_date"`
	TombstonedAt         *string `json:"tombstoned_at,omitempty"`
}

// CreditLimitHistoryListResponse defines model for CreditLimitHistoryListResponse.
type CreditLimitHistoryListResponse struct {
	CreditLimitHistory []CreditLimitHistory `json:"credit_limit_history"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// ExchangeRate defines model for ExchangeRate.
type ExchangeRate struct {
	CreatedAt      string  `json:"created_at"`
	EffectiveDate  string  `json:"effective_date"`
	ExchangeRateId int64   `json:"exchange_rate_id"`
	FromCurrency   string  `json:"from_currency"`
	Rate           string  `json:"rate"`
	ToCurrency     string  `json:"to_currency"`
	TombstonedAt   *string `json:"tombstoned_at,omitempty"`
}

// ExchangeRateListResponse defines model for ExchangeRateListResponse.
type ExchangeRateListResponse struct {
	ExchangeRates []ExchangeRate `json:"exchange_rates"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JournalRecord defines model for JournalRecord.
type JournalRecord struct {
	AccountId            int64                `json:"account_id"`
	Amount               string               `json:"amount"`
	AmountUsd            string               `json:"amount_usd"`
	CategoryId           int64                `json:"category_id"`
	CreatedAt            string               `json:"created_at"`
	Currency             string               `json:"currency"`
	ExternalId           *string              `json:"external_id,omitempty"`
	ExternalSystem       *string              `json:"external_system,omitempty"`
	MemberId             *int64               `json:"member_id,omitempty"`
	Memo                 *string              `json:"memo,omitempty"`
	PendingDate          *string              `json:"pending_date,omitempty"`
	PostedDate           *string              `json:"posted_date,omitempty"`
	PostingStatus        PostingStatus        `json:"posting_status"`
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	RecordId             int64                `json:"record_id"`
	Source               Source               `json:"source"`
	TagIds               []int64              `json:"tag_ids"`
	TombstonedAt         *string              `json:"tombstoned_at,omitempty"`
	TransactionId        int64                `json:"transaction_id"`
	UpdatedAt            string               `json:"updated_at"`
}

// JournalRecordSearchResponse defines model for JournalRecordSearchResponse.
type JournalRecordSearchResponse struct {
	Records []JournalRecord `json:"records"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt    string  `json:"created_at"`
	MemberId     int64   `json:"member_id"`
	Name         string  `json:"name"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// MemberListResponse defines model for MemberListResponse.
type MemberListResponse struct {
	Members []Member `json:"members"`
}

// PostingStatus defines model for PostingStatus.
type PostingStatus string

// ReconciliationStatus defines model for ReconciliationStatus.
type ReconciliationStatus string

// Source defines model for Source.
type Source string

// Tag defines model for Tag.
type Tag struct {
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TagId        int64   `json:"tag_id"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// TagListResponse defines model for TagListResponse.
type TagListResponse struct {
	Tags []Tag `json:"tags"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	CreatedAt     string          `json:"created_at"`
	InitiatedDate string          `json:"initiated_date"`
	Records       []JournalRecord `json:"records"`
	TombstonedAt  *string         `json:"tombstoned_at,omitempty"`
	TransactionId int64           `json:"transaction_id"`
}

// TransactionListResponse defines model for TransactionListResponse.
type TransactionListResponse struct {
	Transactions []Transaction `json:"transactions"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	IsHidden       bool    `json:"is_hidden"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// UpdateExchangeRateRequest defines model for UpdateExchangeRateRequest.
type UpdateExchangeRateRequest struct {
	Rate string `json:"rate"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Name string `json:"name"`
}

// UpdateTagRequest defines model for UpdateTagRequest.
type UpdateTagRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// UpdateTransactionRequest defines model for UpdateTransactionRequest.
type UpdateTransactionRequest struct {
	InitiatedDate string                       `json:"initiated_date"`
	Records       []CreateJournalRecordRequest `json:"records"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	IncludeHidden     *bool                      `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                      `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListAccountsParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListAccountsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                       `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAccountsParamsSort defines parameters for ListAccounts.
type ListAccountsParamsSort string

// ListAccountsParamsSortDir defines parameters for ListAccounts.
type ListAccountsParamsSortDir string

// GetAccountParams defines parameters for GetAccount.
type GetAccountParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListCreditLimitHistoryParams defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParams struct {
	IncludeTombstoned *bool                                `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListCreditLimitHistoryParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListCreditLimitHistoryParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCreditLimitHistoryParamsSort defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParamsSort string

// ListCreditLimitHistoryParamsSortDir defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParamsSortDir string

// SearchAccountJournalRecordsParams defines parameters for SearchAccountJournalRecords.
type SearchAccountJournalRecordsParams struct {
	CategoryId           *int64                `form:"category_id,omitempty" json:"category_id,omitempty"`
	TagId                *int64                `form:"tag_id,omitempty" json:"tag_id,omitempty"`
	MemberId             *int64                `form:"member_id,omitempty" json:"member_id,omitempty"`
	PostingStatus        *PostingStatus        `form:"posting_status,omitempty" json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	AmountMin            *string               `form:"amount_min,omitempty" json:"amount_min,omitempty"`
	AmountMax            *string               `form:"amount_max,omitempty" json:"amount_max,omitempty"`
	AmountUsdMin         *string               `form:"amount_usd_min,omitempty" json:"amount_usd_min,omitempty"`
	AmountUsdMax         *string               `form:"amount_usd_max,omitempty" json:"amount_usd_max,omitempty"`
	InitiatedDateFrom    *string               `form:"initiated_date_from,omitempty" json:"initiated_date_from,omitempty"`
	InitiatedDateTo      *string               `form:"initiated_date_to,omitempty" json:"initiated_date_to,omitempty"`
	PendingDateFrom      *string               `form:"pending_date_from,omitempty" json:"pending_date_from,omitempty"`
	PendingDateTo        *string               `form:"pending_date_to,omitempty" json:"pending_date_to,omitempty"`
	PostedDateFrom       *string               `form:"posted_date_from,omitempty" json:"posted_date_from,omitempty"`
	PostedDateTo         *string               `form:"posted_date_to,omitempty" json:"posted_date_to,omitempty"`
	MemoContains         *string               `form:"memo_contains,omitempty" json:"memo_contains,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	IncludeHidden     *bool                        `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                        `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListCategoriesParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListCategoriesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                         `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCategoriesParamsSort defines parameters for ListCategories.
type ListCategoriesParamsSort string

// ListCategoriesParamsSortDir defines parameters for ListCategories.
type ListCategoriesParamsSortDir string

// GetCategoryParams defines parameters for GetCategory.
type GetCategoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetCreditLimitHistoryParams defines parameters for GetCreditLimitHistory.
type GetCreditLimitHistoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListExchangeRatesParams defines parameters for ListExchangeRates.
type ListExchangeRatesParams struct {
	FromCurrency      *string                         `form:"from_currency,omitempty" json:"from_currency,omitempty"`
	ToCurrency        *string                         `form:"to_currency,omitempty" json:"to_currency,omitempty"`
	EffectiveDate     *string                         `form:"effective_date,omitempty" json:"effective_date,omitempty"`
	IncludeTombstoned *bool                           `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListExchangeRatesParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListExchangeRatesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                            `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExchangeRatesParamsSort defines parameters for ListExchangeRates.
type ListExchangeRatesParamsSort string

// ListExchangeRatesParamsSortDir defines parameters for ListExchangeRates.
type ListExchangeRatesParamsSortDir string

// GetExchangeRateParams defines parameters for GetExchangeRate.
type GetExchangeRateParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	IncludeTombstoned *bool                     `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListMembersParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListMembersParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                      `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMembersParamsSort defines parameters for ListMembers.
type ListMembersParamsSort string

// ListMembersParamsSortDir defines parameters for ListMembers.
type ListMembersParamsSortDir string

// GetMemberParams defines parameters for GetMember.
type GetMemberParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// SearchJournalRecordsParams defines parameters for SearchJournalRecords.
type SearchJournalRecordsParams struct {
	AccountId            *int64                `form:"account_id,omitempty" json:"account_id,omitempty"`
	CategoryId           *int64                `form:"category_id,omitempty" json:"category_id,omitempty"`
	TagId                *int64                `form:"tag_id,omitempty" json:"tag_id,omitempty"`
	MemberId             *int64                `form:"member_id,omitempty" json:"member_id,omitempty"`
	PostingStatus        *PostingStatus        `form:"posting_status,omitempty" json:"posting_status,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	AmountMin            *string               `form:"amount_min,omitempty" json:"amount_min,omitempty"`
	AmountMax            *string               `form:"amount_max,omitempty" json:"amount_max,omitempty"`
	AmountUsdMin         *string               `form:"amount_usd_min,omitempty" json:"amount_usd_min,omitempty"`
	AmountUsdMax         *string               `form:"amount_usd_max,omitempty" json:"amount_usd_max,omitempty"`
	InitiatedDateFrom    *string               `form:"initiated_date_from,omitempty" json:"initiated_date_from,omitempty"`
	InitiatedDateTo      *string               `form:"initiated_date_to,omitempty" json:"initiated_date_to,omitempty"`
	PendingDateFrom      *string               `form:"pending_date_from,omitempty" json:"pending_date_from,omitempty"`
	PendingDateTo        *string               `form:"pending_date_to,omitempty" json:"pending_date_to,omitempty"`
	PostedDateFrom       *string               `form:"posted_date_from,omitempty" json:"posted_date_from,omitempty"`
	PostedDateTo         *string               `form:"posted_date_to,omitempty" json:"posted_date_to,omitempty"`
	MemoContains         *string               `form:"memo_contains,omitempty" json:"memo_contains,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	IncludeHidden     *bool                  `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool                  `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
	Sort              *ListTagsParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	SortDir           *ListTagsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Limit             *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int                   `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTagsParamsSort defines parameters for ListTags.
type ListTagsParamsSort string

// ListTagsParamsSortDir defines parameters for ListTags.
type ListTagsParamsSortDir string

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreateCreditLimitHistoryJSONRequestBody defines body for CreateCreditLimitHistory for application/json ContentType.
type CreateCreditLimitHistoryJSONRequestBody = CreateCreditLimitHistoryRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CreateExchangeRateJSONRequestBody defines body for CreateExchangeRate for application/json ContentType.
type CreateExchangeRateJSONRequestBody = CreateExchangeRateRequest

// UpdateExchangeRateJSONRequestBody defines body for UpdateExchangeRate for application/json ContentType.
type UpdateExchangeRateJSONRequestBody = UpdateExchangeRateRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// BulkReassignJournalRecordAccountJSONRequestBody defines body for BulkReassignJournalRecordAccount for application/json ContentType.
type BulkReassignJournalRecordAccountJSONRequestBody = BulkReassignRecordsAccountRequest

// BulkCategorizeJournalRecordsJSONRequestBody defines body for BulkCategorizeJournalRecords for application/json ContentType.
type BulkCategorizeJournalRecordsJSONRequestBody = BulkCategorizeRecordsRequest

// BulkUpdateJournalRecordStatusesJSONRequestBody defines body for BulkUpdateJournalRecordStatuses for application/json ContentType.
type BulkUpdateJournalRecordStatusesJSONRequestBody = BulkUpdateRecordStatusRequest

// BulkUpdateJournalRecordTagsJSONRequestBody defines body for BulkUpdateJournalRecordTags for application/json ContentType.
type BulkUpdateJournalRecordTagsJSONRequestBody = BulkTagRecordsRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// ReplaceTransactionJSONRequestBody defines body for ReplaceTransaction for application/json ContentType.
type ReplaceTransactionJSONRequestBody = UpdateTransactionRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7B1Zc9u4+a9g2H3YzsiWnTh7+GXHu90jnc02ddyXZlMNTEISNiShAKATxdV/7+AiAQq8JJKSu3qyzAP4",
	"7gPfB/AxCEmyIilKOQuuHwOK2IqkDMl/fiDpPMYhF79DknKUyp9wtYpxCDkm6fQPRlJxjYVLlEDx6wuK",
	"5sF18JdpMfBU3WXTHykl9FZPEWw2m0kQIRZSvBKDBdfB3RIBij5kiHEQ6tkZ+Ij5EqBPmHGcLgDjkKPz",
	"YDMJXqYPMMbRrXrhMFBiBrACQ4L0CvEliX4j/CaOyUcUjQwUyTgCEUEMpIQDlq1WhHLAC3hRBBIJooT2",
	"N8J/IlkaHYR0KAIUMZLREIGPUEE8F9CcB+I9PaSY8eb1SzmwhC2KsBgLxq8pWSHKsZDVOYwZmgQr65LA",
	"KELiL0qzJLh+G2g+zfT8wSRICZ/JKYNJoMgyE5eg5t0kMDIYTAKcckRTGM+QBOXdJODrFQquA8YpTheC",
	"nAliDC7knKV7m0kgZsVUSMRbBVnxfDEWuf8DhVyMdROGJNPsaI8yVG/NsGTpnNAE8uBawP7VVZDPIlBZ",
	"ICqmCSmCHEUzyD1QT4IwoxSl4VrcTLM4hvcxCq45zcTMkAuKBNfBf97enP373ePzzReBhyrokyacAqo8",
	"TPXzbM04Slq9M/+QeuHHbLbEUYTsu/eExAim4vZ7rGR/670YPaDYumNRLIUJ8r6zghSlfKZBaQSZk+Se",
	"cZLmxG98I1tF1bwqSZglCIo6GlmbJBoXg60jDM5sNfL5K2Y81/edZFX+xhwlrMm4GJXY5OBASuG6Cnfm",
	"hfv7LH7/A+RoQSj+jG5RSGjELA/Sxb6oYdZV2pbgFCfC9Fz6NI/KqWc4cgnQcZQEpy/Vq5clqkyCLMUf",
	"MqRvC5kqE8oCYeJgU0W4WwQZw4tUk00zZDfqNZiqp0U8C5lq2onn/7FCVDrWHZWmLeLbyLoqU+h37mZy",
	"Wl1sv16HuztQFfp3cNFR2dzA4TUlDzhCAHIQI8g4ICkCKUnPULLiawCjaMbhQoAECAUUJeQB5Vck0udA",
	"BB/8I1H/MpBkjMuogzwgGsPVuRIYG5RnW1JbzDOe5B1G3sWsNhWPQdOqpOtfUgaVgL3hkGd7StmKyFxj",
	"xuRYEyBASEMcY6m7+WVCwT3hyzaC447Y5Opeq6cVKsbgbQHQNMqt85I72PFYTx9PtYde9+yRO8e/O8aV",
	"Tz58tAlp4seeAkfD2j0iRw2d/q9V7JgLVFPwaI3thV5iulfg83+VU0VoDrOY56iWdaFEXTFmNVkNk3aj",
	"6wHgpSjC/FecYP4LZnxnyEM5ziwWA8lIDH76FaULvgyuL791heLi7Nt3j5eTy282X/7++7n595vNX7/z",
	"y8l8jkKOH9BM6KT0Q+XBrjZn6sez4odnrLKa2CBvzVNNsh8/hUuYLtCtdNe7EKs/lCbBnJJkZutjW/2j",
	"eur+OMXJDoCUpdVBxx1Tw9yBVX8nmTAZKqg6QI4HkzwzKaj87MKh8tl3X1qE/m/+++tNQXPr8lfW5ckz",
	"68YL+8Zz68aVfePKuvHcvvHCuvHMvvGVdePSvvG1deNi4wqIVz4UNWYZi04U0WuTey2/7KL1Y3jdBCX3",
	"iLbBqWIoO0JHCWk16QqlkUhOjEWtC0u6WViR9qBooIGPJZ9SRYymt9+op4St3z+hbrMAqoJ3ywNoi+oY",
	"k0kp1i/RtYpSOdLV/uOVlOTdHEdFllTCUz5VDYBccnoakeQdhSmDoVoY3AVknGKOoa1qu6uWys075FbV",
	"4YKzTPCsQWxLOBSAVNCtFHsfulQ2WBBvjzxbKmTbg91nvNx10aEmabARmZQsVm1u4TCinWTss9TgAbmL",
	"YpRltHH5wTefD0u30t4xhTLF9Npqmym6l0Es178tmKzkrjud65SrTyFGGsqZSIja69FTzxX31t4tuk12",
	"Sjgb9deWoj001wG3vTNzZLhJW0tz+LD5BcGYL3fEoQhLTQ8Lee/pPClBpd/yQeM46aEd5imBPyXw+yTw",
	"e3UrPZ2c/pTHH11dtKU4DpL3N3dudC/98SK9bI9dl3phQbmtySZ7LUcYknVfmOhWlXQc4xsEabjcq0On",
	"fcDhuuSmiKMuJVYLLv0G3vWmq0N5e9h6dQFmXpvuwn1FuT2CTTV/e6ZrVjVx2wzrg9k1hVaIqJ1AYIy2",
	"1Kk0RHGMIm/bstccWgMaRZNDZan1r2+0N7lRNO8nMM1g7H34Di76ldcjbtiQlqytyR9UWzQoPTd23MHF",
	"HhrE4aK9+gixadIdOaAXzsI/9St7h1yDbfAiIwUNZRaUI4GtFV5Hvup8m8W0fYSsGKWDsFny0ih09gQ+",
	"PFSj4l79Q2NkLLXmsrxsnz9bjfB+nT19Q7N/E0rfa3rlKK+qM0PBf8DKmgJg58pa35w81c261c020k3N",
	"5WoCx1xYgOAVTiG4/fHNHbh5/TKYBA+IMtUNfXF+eX4hYCErlMIVDq6D5+cX588DKelLieDU3sazQJL+",
	"xGxyeBkF14Gw1zfmIRk2wQRxGS2/FQwIroMPGaJrE30IfxLGWYSKqKTYfNhcda0fsnCDvQzLCOX+gXRs",
	"ZWJg9V9zOFXoY/WEswjTikkhC61J1X8RYmGHGUzZrRg+gZ9UJ8KLi4v6voSqMcl8zlBp0LrdJu8m7kbk",
	"ZxcXvW1R9W1c82xUNRILcAoiIa4CYMZxCH7652+A0AhRuYX2SoHmmzFHYVraqCy3t2ZJAula6wcwWnRu",
	"1sS29chpPQ6UCUCMf0+idW/E8bY3b1yDk28OcRh02TeDapgCtB7tzgDx2rfNr+Ub4F2OKSoBmBq2qR3L",
	"uSmcPhZLXhuloDFS3sVl6d/kdZulDk2v1Ls+ChR2bD8iXDW/lm8Sd4lwZyBw6TDxO4GfES/Q7OACdrXX",
	"I1iQOgE1+9gPwpmfES/zxEdx4cILgjuLtK6y24Tv1KYmuLCCPFxuy4OTBw1kzLy5VitjNqqs6DjgUNKi",
	"qGSkBaiYSx2yAWAaAZM+AhyhlOM5RpTV2bupamE5k3HEmdUyUxkcetpkRrER3WO6rVYGE2m163E4BXdD",
	"B3cNvV8eLVRvAEkYoKVVxHw5R8+keuwZ8O2nojJCDH2Azgk9IlNfE7Z6dXy4CLZ6Z9bIwayvBbClEKKU",
	"03U/oW4n0esnNvbLq8Sp1ntYiyheh6Fqs9p3OmsnLRcX3PryruJeYQvzykrP49r1zZ6H3qqrtxPsUidG",
	"1eiVRfpWk/gbNarm0m0ECU7LHu5P3mrVRDD46USwLgTLWHSSsp2IdpK0lkRz1/Rnc0oSh3K7b+NuNR8n",
	"g85m9ykOj5sz29CYFX2SIyBmTTYwXglKyExExBCnrv8uDzBkelfXpecJq19BHi5xugBQZnL5GoeOMdW5",
	"ohop8ZhVvderHXzd0yK/AtYA8ofCIwdEpHFyJfUI8jgRmrsHrFQv3BSPnep6p7regZd+fOcK+XLtXGhH",
	"Ku0VytRY3MtPKRp0baTUizP2ikh+ElMlb9bHUuAzvDNLFgUrp4/WOkKLGp/D2aYiX06Go6ry2cSorvJZ",
	"iD7xMl8rQT18oc9lS3PU4K5/jVXpG9iy+bsMR671tRKY46j2GSFwyn3GyHnqd9PHir37bUyff+m/0QhW",
	"r4kfmVmsW+iuMZQHqnqOW37rWO04BnNaz84WBrbylIteczSz9/ws399emafZ/c4tU7Xyzn7/ykLdyXQV",
	"BRIyxKhb5fchF8rGTjgNvWYrKPNDkwWWr9cfxnDqUDiONLXydAuPoTTPAqni2+mqYe+0jxaF7cQVOdM3",
	"Jq/OyRlDJrC+7RsjJ7HuKSENnDuedlWHozrcc/3I9LF8zEuLCG+L802xnUueI+tlLROpOoQr4f3Eg7du",
	"Mn0MHa7bnGqOzjynGI2VA49gIKv3t42cC3cTpiNpgS1JFHiAcWbM5FKe41QZZv+MuDrpKRiQqKWzpCo+",
	"r7aiJESMAcwAfIBYbvTUlH3RTKKtD9i5pLpF8otyZg5FFU0i6xCEylTklX7mSBt89fZ3E8G2PkriFDcP",
	"HTd7jujwVXyVeG2HygKj/iPkJckYWpI4Alr2G4NkffDHkOGxuzt45MDYHGxSxZqjqeyUWefasOlj3nHZ",
	"Iv61mNoU+WoqHNcKpocW1UFvjuwTD3cbJfUI1iK9jGmOce1u4bGC20ENm+/Yg5ED2kZxGT+G3c8S6qC3",
	"LGLSU2pj2K4Xf5cmfKd1qeeG9lOD/6nB/9RFfGrwPzX4nxr8Tw3+pwb/U4P/n6bBv9xXj1Onp7/3Mmlt",
	"V78bRE/vs/i92fNqPgi8HVLbX1l3iDHsURnNH3cfOd2q+2K6RxDUo/kpSoBqXPbJxxxO38jh7E0agBPA",
	"UIxCjqI2rA+tTxpX8950p39GW2nVUHwvpix9oP0psJzl7fWfh+B1WHRid2J2cQ59NatVAu5aPPkaGpLb",
	"1V9KfxIazjSF9l9u8S2G6FRZnnvjJrbFxOJ3B0kw5xp3koM78dJwMiCP73xyqg4EKXvm+00UaWYn5AGp",
	"GZoZbHhaWeXU/DttiTvVTA9ZMy2fyO5rGBASP84+OKE1jfXRO7gYtDhqnVw8cmVUnlnvZcDR1EQ5XFgW",
	"bvqoFrtbFEAN15qqnwLZ4yp9KpSrq50Ksyde6qwRvSMochoWNNc18+LLWEXN4azR1jnqI0dgNSJxHM14",
	"HC58m9PKX3CoDsHsB4ckZMWHKXzEtUASPjdfknWPGPR4TvtFeWjFdlza4Fatb1gM6l63z+Mf283aX+uo",
	"5cH+btfvRe9hDNMQRTbbPNI7fXQ/j9LGzZa42OhuLWSPzO1akIn8C3PmlelKt1xHiYtDCNMxOFILnGor",
	"0exly1/t6dPbZnxbTG/RKoah3OBk16ikYPAlAvMsjku4ACYw5iTBIYzj9Tm4WyLgAg4wAyuKGKIPKJqI",
	"nw+YZMws1psSAaT2BpSJXg2QACXIOisoyRg3qg04AZ8RJaCofJ4Hk5KUaqyGt7yVX0IZO6RoryyawAfT",
	"F82b1oZos9n8LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
