// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeConflict         APIErrorCode = "conflict"
	APIErrorCodeInternalError    APIErrorCode = "internal_error"
	APIErrorCodeInvalidRequest   APIErrorCode = "invalid_request"
	APIErrorCodeMethodNotAllowed APIErrorCode = "method_not_allowed"
	APIErrorCodeNotFound         APIErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeConflict:
		return true
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidRequest:
		return true
	case APIErrorCodeMethodNotAllowed:
		return true
	case APIErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// Category defines model for Category.
type Category struct {
	CategoryId   int64   `json:"category_id"`
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Categories []Category `json:"categories"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	IncludeHidden     *bool `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetCategoryParams defines parameters for GetCategory.
type GetCategoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFjfb+M2DP5XBG6PRpLuugHzW9fddQV2Rdd1T8UhUC0m0c2WXIluFxT+3wfKjn/FTS69XntPcSyL/PiR",
	"+kj7ERKb5dagIQ/xIzj0uTUew59TaxapToivE2sITbiUeZ7qRJK2ZvrZW8P3fLLCTPLVjw4XEMMP09bw",
	"tFr10/fOWXdVu4CyLCNQ6BOnczYGMVyvUDi8K9CTSGrvXjxoWgn8T3vSZik8ScIJlBGcm3uZanVVbXgb",
	"lNoLXcEIkD4iray6sHSSpvYB1SuDsgWhUBa9MJaEL/LcOhLU4kUlsgAxoL2w9MEWRr0JdaiEQ28Ll6B4",
	"kBXiBaOZAO+rTbLHk8vzYDhgU0qzLZleOpujI821upCpxwjyzi2OSCH/oikyiG+gztO89g8RGEvz4BIi",
	"qGiZ8y1Z5y6CTQ1CBNoQOiPTOQYonyKgdY4QgyenzZLpzNB7uQw+B2tlBOxVO66ImwpZ+3xry95+xoTY",
	"1qkkXFq3PjTmettch6QurMskQczofzmGxg8Hs0THjhKHklDNJY3gjmBxZ0bvaz9faaWwu3prbYrS8HKK",
	"95h2ljoOjcxw1GQuHRqa1x5NkabyNkWIyRU4wjbZ7NaTNQ32vTuKXD0d6jBFHSIrFrox11Fs4uyx2POz",
	"K7V/ak/NWXlWmut/mjDz+45mU1BlA0k6J9dPRc62R9GHSDfWOtp7APwvKiqFC1mk1JgYFtkANtscw9uX",
	"pMNw4kZ1dhHbqNMQ0VAoWkx/oExp9UxQ3P8K3xU2+++IHA3A1LvG0PwTyvXrMrpTDgZQ2me30fCz2ixs",
	"MKOJDzN81EaKq/d/X4uTy3OI4B6dr7rJbHI0mXEINkcjcw0xvJvMJu+AxYRWAdm0f1aWGEJj7KHBnSuI",
	"gU/iaftYkCKZIaHzEN88gmZndwW69ebks6IlaaGwVYS2Q+6v3N0mW2U7zOynqD+//TSbvVhnHxWtkQbf",
	"0ii0EYo5zLTh0S0RH/66ENYpdGH4OK7QjTltopgORrwwGBRZJrkxhrSJNr3Bam79SIL7ogVVPaKn36xa",
	"vxxFo8pY9sufW1O5laejF8/TjtysRd2tnp8G3vbr/m3NC0Q/bxVRQm5yt64mvs5JnT52+m9ZFX+KhNuZ",
	"/T3c72W2x+xxtXmUhvacfR0Tx/u3NZN2n4nrDYI+GdG4TJ0hdQI9QKO+Z0HZWaib94E3Sc4Z0jAtY5xz",
	"p2kp78+N/XPf5X5rMmeVzLifH21P6ZyIXFKy2q6JfvP+Rso2PiF8kbK9csHUo/dblUxFVFMzohoOmk8W",
	"LHKrMPs9OYqcIVXTIXxDKgfz5xPv6bmzCXovtBfyXurwblUT+/N+hra+hPSZusLwaWLjo2KFKSrL/wMA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
