// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeConflict         APIErrorCode = "conflict"
	APIErrorCodeInternalError    APIErrorCode = "internal_error"
	APIErrorCodeInvalidRequest   APIErrorCode = "invalid_request"
	APIErrorCodeMethodNotAllowed APIErrorCode = "method_not_allowed"
	APIErrorCodeNotFound         APIErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeConflict:
		return true
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidRequest:
		return true
	case APIErrorCodeMethodNotAllowed:
		return true
	case APIErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// Account defines model for Account.
type Account struct {
	AccountId      int64   `json:"account_id"`
	CreatedAt      string  `json:"created_at"`
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       bool    `json:"is_hidden"`
	Kind           string  `json:"kind"`
	Level          int     `json:"level"`
	Name           string  `json:"name"`
	ParentFqn      *string `json:"parent_fqn,omitempty"`
	TombstonedAt   *string `json:"tombstoned_at,omitempty"`
	UpdatedAt      string  `json:"updated_at"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Accounts []Account `json:"accounts"`
}

// Category defines model for Category.
type Category struct {
	CategoryId   int64   `json:"category_id"`
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Categories []Category `json:"categories"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Currency       *string `json:"currency,omitempty"`
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	Fqn            string  `json:"fqn"`
	IsHidden       *bool   `json:"is_hidden,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreateCreditLimitHistoryRequest defines model for CreateCreditLimitHistoryRequest.
type CreateCreditLimitHistoryRequest struct {
	CreditLimit   string `json:"credit_limit"`
	EffectiveDate string `json:"effective_date"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	Name string `json:"name"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Fqn      string `json:"fqn"`
	IsHidden *bool  `json:"is_hidden,omitempty"`
}

// CreditLimitHistory defines model for CreditLimitHistory.
type CreditLimitHistory struct {
	AccountId            int64   `json:"account_id"`
	CreatedAt            string  `json:"created_at"`
	CreditLimit          string  `json:"credit_limit"`
	CreditLimitHistoryId int64   `json:"credit_limit_history_id"`
	EffectiveDate        string  `json:"effective_date"`
	TombstonedAt         *string `json:"tombstoned_at,omitempty"`
}

// CreditLimitHistoryListResponse defines model for CreditLimitHistoryListResponse.
type CreditLimitHistoryListResponse struct {
	CreditLimitHistory []CreditLimitHistory `json:"credit_limit_history"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Member defines model for Member.
type Member struct {
	CreatedAt    string  `json:"created_at"`
	MemberId     int64   `json:"member_id"`
	Name         string  `json:"name"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// MemberListResponse defines model for MemberListResponse.
type MemberListResponse struct {
	Members []Member `json:"members"`
}

// Tag defines model for Tag.
type Tag struct {
	CreatedAt    string  `json:"created_at"`
	Fqn          string  `json:"fqn"`
	IsHidden     bool    `json:"is_hidden"`
	Level        int     `json:"level"`
	Name         string  `json:"name"`
	ParentFqn    *string `json:"parent_fqn,omitempty"`
	TagId        int64   `json:"tag_id"`
	TombstonedAt *string `json:"tombstoned_at,omitempty"`
	UpdatedAt    string  `json:"updated_at"`
}

// TagListResponse defines model for TagListResponse.
type TagListResponse struct {
	Tags []Tag `json:"tags"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	ExternalId     *string `json:"external_id,omitempty"`
	ExternalSystem *string `json:"external_system,omitempty"`
	IsHidden       bool    `json:"is_hidden"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Name string `json:"name"`
}

// UpdateTagRequest defines model for UpdateTagRequest.
type UpdateTagRequest struct {
	IsHidden bool `json:"is_hidden"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	IncludeHidden     *bool `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetAccountParams defines parameters for GetAccount.
type GetAccountParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListCreditLimitHistoryParams defines parameters for ListCreditLimitHistory.
type ListCreditLimitHistoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	IncludeHidden     *bool `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetCategoryParams defines parameters for GetCategory.
type GetCategoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetCreditLimitHistoryParams defines parameters for GetCreditLimitHistory.
type GetCreditLimitHistoryParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetMemberParams defines parameters for GetMember.
type GetMemberParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	IncludeHidden     *bool `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	IncludeTombstoned *bool `form:"include_tombstoned,omitempty" json:"include_tombstoned,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreateCreditLimitHistoryJSONRequestBody defines body for CreateCreditLimitHistory for application/json ContentType.
type CreateCreditLimitHistoryJSONRequestBody = CreateCreditLimitHistoryRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftbc9u6Ef4rHPQ8tDOyZZ+4nUQvHTfNxTNxJnXVlzquBiZXEhISYADQiUaj/97BhVeBF90oOSdPlkQC",
	"+Hb3w+JbAF4in0Uxo0ClQKMl4iBiRgXoL68ZnYbEl+qzz6gEqj/iOA6JjyVhdPhFMKp+E/4cIqw+/cZh",
	"ikboT8O846F5KoZvOGf8zg6BVqvVAAUgfE5i1RkaofEcPA7fEhDS8+3owvtO5NyDH0RIQmeekFjCOVoN",
	"0A19wiEJ7kyD46AkwiMGhoZ0C3LOgo9MXoch+w5Bz6BYIsELGAiPMumJJI4Zl57M8ULgRRqiRvuRybcs",
	"ocFRXAeBx0GwhPvgfccG8VShOUeqne1SjXj96UZ3rLEFAVF94fATZzFwSRRXpzgUMEBx4SdlUQDqL9Ak",
	"QqN7ZOM0seOjAaJMTvSQaICMWybqJ2xjN0ApB9EAESqBUxxOQEN5GCC5iAGNkJCc0JlyZwRC4Jkes/Js",
	"NUBqVMIVI+4Nsvz9vC/2+AV8qfq69n2W2HB0NxmbVhOiQzplPMISjRT2v12hbBRlygy4GsbngCUEEywd",
	"qAfITzgH6i/UQ5qEIX4MAY0kT9TIWCqPoBH63/312X8fli9WvyGHV+CHdZwBVe2m/n2xEBKiTm2m36gT",
	"PxGTOQkCKD59ZCwETNXjr8Rwf61dCE8QFp4UPEZxBM42MeZA5cRCaYUsWfQoJKOZ81tbJHFQH6sKwwpE",
	"MN6xxhZdYm1JrS2RoTRaAz8/ECGz+b4VV/VnIiESbcklnRKrDA7mHC/qbBdO3K+xhBnji01ziW22t5m1",
	"JWOfPTGLjkyZuSdKpqHdgZMWnf3WiZUZodpoWejbiV5bajlekDSboP+ZsnUAU5yEMjO1Ohcq3lV91rs1",
	"DdJ2fj0CXg4BkR9IROR7IuTWyH3dzyRUHanvEf7xAehMztHo8lWZFBdnrx6Wl4PLl6s/f/58nn59ufrL",
	"3908mU7Bl+QJJmpOqr7XOrtanZkPv+cfHH1Vp0kR8to49S67hegR+HZuqkmdFWT6rXoAYzx7FvSqEOvY",
	"CvNgDC32PJkbY7vD3h+/N19RG2ZE0ZBBWeU1T5xSILoxY5d11AG5+4q6ztHWtdU1nsvKcoG6mVGQ1qCN",
	"IjWtVasQq2Vjjuk94FDOtwQlJJaJKJa57KujOK2Asa1caEwe3TzeTZM80n12n3y1Uvaw2jSHmenQTfSn",
	"8dwOs8aM31162lC1TY60WxfmMZ7tN9QnXNfgWXcGHpZoFsqe658xnu1APoln3ZmnaNNGO92hC+d/tBk7",
	"VTp9VCmNjK3Ymr9bb/BuNci+0RxRLhsAW8vlfXlCvUvolOluiFRMQLeEYu/uzb/H3vWnGzRAT8CF2bi+",
	"OL88v1DoWQwUxwSN0Ivzi/MXSGvUuUY2LG5pzUAbppDrnfSbAI2Qmp/X6Us6g+EIpM7590tE1EDfEuCL",
	"NBGonOSHSQB5gsg34ttLguYu8xy3WbcPg/Ix0e8XF3s7QHBtKzqOEVIfeoR6gXJgRCgRkvje23999BgP",
	"gOsDjisDzTViZsKwcoykDx+SKMJKsuqIeWlcdZ8xE47IlrZvkGEhCPkPFiz25hznFtGqzHmVzFZrAbrc",
	"d4AaguLZNWv7AKhmr9qbZceT5YgZL3mYpmEz50nZ5Bwu87JpZQgfginxyiH9p/69GNKST69MW5cH8pm1",
	"mxOu2ptlR3hlJ4xTBGU/DNxp6R3I3MwNktIJZ5AmgqanjEeJzDuQ1Zi4PK4WldzhpUK/PNmLjl8Ttiot",
	"RqosvFwXuSoKMZb+fJ0PJYV2oGTmVIGdklmvXLGa+1hsMV5K2eIZFWCuQHiYBl4qbD0SAJVkSoCLpnw3",
	"NDslZ3qn5KywM1MrVxy7Mc8+R7TsdTnoYFp42m2edZsSH9ku25mO047KYzeuaKniu4BOGT+hnNOgn5xk",
	"O5yUqj9m6VlVubY8O5IQqOSL/Wiujai3H5Hm5qu2yaax8pFsfZrKX/tVV9WfUrfmucyNPZVWeXhbi6vs",
	"pP2gKaGyS9N3IshuE9TGZnEqBVYau/WZOlwWrnl0qLFKkW0rsjI3nFSVVXRGfZVVMPS5S6guRD1+oVUO",
	"S7voKV9P6qvSOnBmc+8/91xrdSLMaVRbKQlK5Vaa5Bz103BZc0TfJfW5FW9rEqyXgieWFpv0XUOi/ENU",
	"nRuK/FNIp83h7JBgay+z7C3Zqmk613cqaiuGdyDNrQt0wHhX7nXU/DdEzJkPQnhEePgJE30maWP81/Zg",
	"rf2/STlod6D/ASQdw3jFZrLCbYPaqurWvvPs557jboYjHtbc9dJHWbj/2mfOEgFzFgaejUVrCWRvfByy",
	"ACofDPdc/qQ3WupCczKlTzV05Tk1XGZXiTpIgEJQ25Z964XTWuIdvqhf2DNjf4qE0sDUE1isnYFpX6KL",
	"1+D6qoAOmthcN156rn5a6dJ/5bNbJrSlUpVieqW0yTC9UVarLsbqhV+7tc7rdW1SRfmupy1aFcdWZTLG",
	"s4PKksJ1sZ41ib7r6AzAyagRiWeFOTdcmvulHaRHGrU23aGMPS3RYUyu1xnGsmcuMhqodwLyIg1Bu6LI",
	"7jv3JScOl43WLq/2LCQaKHEam6cSz9b2TVer/wcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
