// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for APIErrorCode.
const (
	APIErrorCodeInternalError    APIErrorCode = "internal_error"
	APIErrorCodeInvalidRequest   APIErrorCode = "invalid_request"
	APIErrorCodeMethodNotAllowed APIErrorCode = "method_not_allowed"
	APIErrorCodeNotFound         APIErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the APIErrorCode enum.
func (e APIErrorCode) Valid() bool {
	switch e {
	case APIErrorCodeInternalError:
		return true
	case APIErrorCodeInvalidRequest:
		return true
	case APIErrorCodeMethodNotAllowed:
		return true
	case APIErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    APIErrorCode `json:"code"`
	Message string       `json:"message"`
}

// APIErrorCode defines model for APIError.Code.
type APIErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"rFPNbtswDH4Vg9vRsL11u/jWQ7Hl0CHIeiuGQLWYWJ0saiKdoSj87gPltGnddcCGncKQEr8f+buHjoZI",
	"AYMwtPeQkCMFxvznEqUn+4Xk3Hv6iVZ7HQXBIFqaGL3rjDgK9S1T0B53PQ5Gq7cJd9DCm/oEUM9Tri9S",
	"orQ5QsE0TSVY5C65qMughasei0SjYGEJuQgkBY8xUpJCdIQ/RmRBWwyZYgW64rhdwc/Xq4yRaVrrdK3x",
	"60QRkzhVtzOesYT4pKXiLOovhnGA9hpcOBjv7PaIByUEku2OxmChhBl7qy1zNKgEFwRTMH6LGf9bCXIX",
	"EVpgSS7sYdJ7zGafgRazqQSFckm9vp7pnM6fdtHNLXaiu547+Xdq8cGhPz3Vo5NLckt9J06f0Xjp/5EU",
	"i5GRnz4Cff+Niwsyx1sv2ehBF3aUzXbidXbpgik2F1+vivP1Cko4YOL5s2uqd1WjEihiMNFBC2dVU51B",
	"CdFIn2nVfZan5R5zDpR+TsHKQgufUGYDoHyepvdN898CtLD4lQTFRB0yF44LczDOmxuPlcr70Hx8DeGR",
	"cv0i/Tlj4zCYdActbDDH8QFjdkWDOE2/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
