package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

type generatedOperation struct {
	id             string
	info           operationInfo
	decisions      operationConfig
	definition     codegen.OperationDefinition
	mcpInputSchema []byte
}

func generate(
	outputPath string,
	document *openapi3.T,
	config surfaceConfig,
	operations map[string]operationInfo,
) error {
	if err := initializeCodegen(document); err != nil {
		return err
	}
	definitions, err := codegen.OperationDefinitions(document)
	if err != nil {
		return fmt.Errorf("describe generated client operations: %w", err)
	}
	definitionsByID := make(map[string]codegen.OperationDefinition, len(definitions))
	for _, definition := range definitions {
		definitionsByID[definition.SpecOperationId] = definition
	}

	operationIDs := make([]string, 0, len(config.Operations))
	for operationID, decisions := range config.Operations {
		if isExposed(decisions) {
			operationIDs = append(operationIDs, operationID)
		}
	}
	sort.Strings(operationIDs)

	generated := make([]generatedOperation, 0, len(operationIDs))
	for _, operationID := range operationIDs {
		definition, ok := definitionsByID[operationID]
		if !ok {
			return fmt.Errorf("OpenAPI operation %s has no generated client definition", operationID)
		}
		item := generatedOperation{
			id:         operationID,
			info:       operations[operationID],
			decisions:  config.Operations[operationID],
			definition: definition,
		}
		if decision := item.decisions.MCP; decision != nil && decision.State == "exposed" {
			item.mcpInputSchema, err = buildMCPInputSchema(definition)
			if err != nil {
				return fmt.Errorf("build MCP input schema for %s: %w", operationID, err)
			}
		}
		generated = append(generated, item)
	}

	var output bytes.Buffer
	writeHeader(&output, generated)
	writeCatalog(&output, generated)
	writeHelpers(&output)
	for _, operation := range generated {
		writeInvoker(&output, operation)
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated output: %w", err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

func initializeCodegen(document *openapi3.T) error {
	encoded, err := json.Marshal(document)
	if err != nil {
		return fmt.Errorf("copy OpenAPI document for client type generation: %w", err)
	}
	documentCopy, err := openapi3.NewLoader().LoadFromData(encoded)
	if err != nil {
		return fmt.Errorf("load OpenAPI document copy for client type generation: %w", err)
	}
	_, err = codegen.Generate(documentCopy, codegen.Configuration{
		PackageName: "httpclient",
		Generate: codegen.GenerateOptions{
			Client: true,
			Models: true,
		},
	})
	if err != nil {
		return fmt.Errorf("initialize generated client type descriptions: %w", err)
	}
	return nil
}

func isExposed(decisions operationConfig) bool {
	return decisions.CLI != nil && decisions.CLI.State == "exposed" ||
		decisions.MCP != nil && decisions.MCP.State == "exposed"
}

func writeHeader(output *bytes.Buffer, operations []generatedOperation) {
	imports := []string{
		"context",
		"encoding/json",
		"errors",
		"fmt",
		"net/http",
		"sort",
	}
	usesBody := false
	usesOpenAPITypes := false
	usesTime := false
	for _, operation := range operations {
		usesBody = usesBody || operation.definition.HasBody()
		for _, parameter := range operation.definition.AllParams() {
			typeName := parameter.TypeDef()
			usesOpenAPITypes = usesOpenAPITypes || strings.Contains(typeName, "openapi_types.")
			usesTime = usesTime || strings.Contains(typeName, "time.")
		}
	}
	if usesBody {
		imports = append(imports, "bytes")
	}
	if usesTime {
		imports = append(imports, "time")
	}
	sort.Strings(imports)

	fmt.Fprintln(output, "// Code generated by surfacegen. DO NOT EDIT.")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "package httpclient")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "import (")
	for _, importPath := range imports {
		fmt.Fprintf(output, "\t%q\n", importPath)
	}
	if usesOpenAPITypes {
		fmt.Fprintln(output)
		fmt.Fprintln(output, "\topenapi_types \"github.com/oapi-codegen/runtime/types\"")
	}
	fmt.Fprintln(output, ")")
	fmt.Fprintln(output)
}

func writeCatalog(output *bytes.Buffer, operations []generatedOperation) {
	fmt.Fprintln(output, "// Operations returns the generated catalog of operations exposed on at least one client surface.")
	fmt.Fprintln(output, "func Operations() []Operation {")
	fmt.Fprintln(output, "\treturn []Operation{")
	for _, operation := range operations {
		writeOperation(output, operation)
	}
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	writeSurfaceCatalog(output, "CLI", operations, func(operation generatedOperation) bool {
		return operation.decisions.CLI != nil && operation.decisions.CLI.State == "exposed"
	})
	writeSurfaceCatalog(output, "MCP", operations, func(operation generatedOperation) bool {
		return operation.decisions.MCP != nil && operation.decisions.MCP.State == "exposed"
	})
}

func writeSurfaceCatalog(
	output *bytes.Buffer,
	surface string,
	operations []generatedOperation,
	included func(generatedOperation) bool,
) {
	fmt.Fprintf(output, "// %sOperations returns the generated catalog subset exposed on the %s surface.\n", surface, surface)
	fmt.Fprintf(output, "func %sOperations() []Operation {\n", surface)
	fmt.Fprintln(output, "\toperations := Operations()")
	fmt.Fprintln(output, "\treturn []Operation{")
	for index, operation := range operations {
		if included(operation) {
			fmt.Fprintf(output, "\t\toperations[%d],\n", index)
		}
	}
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func writeOperation(output *bytes.Buffer, generated generatedOperation) {
	operation := generated.info.operation
	fmt.Fprintln(output, "\t\t{")
	fmt.Fprintf(output, "\t\t\tID: %q,\n", generated.id)
	fmt.Fprintf(output, "\t\t\tMethod: %q,\n", generated.info.method)
	fmt.Fprintf(output, "\t\t\tPath: %q,\n", generated.info.path)
	fmt.Fprintf(output, "\t\t\tSummary: %q,\n", operation.Summary)
	fmt.Fprintf(output, "\t\t\tDescription: %q,\n", operation.Description)
	if decision := generated.decisions.CLI; decision != nil && decision.State == "exposed" {
		area, _ := resolveCLI("", generated.id, operation, decision)
		if decision.Completion == nil {
			fmt.Fprintf(output, "\t\t\tCLI: &CLIOperation{Area: %q, Name: %q},\n", area, decision.Name)
		} else {
			completion := decision.Completion
			fmt.Fprintln(output, "\t\t\tCLI: &CLIOperation{")
			fmt.Fprintf(output, "\t\t\t\tArea: %q, Name: %q,\n", area, decision.Name)
			fmt.Fprintln(output, "\t\t\t\tCompletion: &CLICompletion{")
			fmt.Fprintf(output, "\t\t\t\t\tStatusOperationID: %q,\n", completion.StatusOperationID)
			fmt.Fprintf(output, "\t\t\t\t\tRunIDResponseField: %q,\n", completion.RunIDResponseField)
			fmt.Fprintf(output, "\t\t\t\t\tStatusPathParameter: %q,\n", completion.StatusPathParameter)
			fmt.Fprintf(output, "\t\t\t\t\tTerminalField: %q,\n", completion.TerminalField)
			writeStringSliceField(output, "\t\t\t\t\t", "TerminalValues", completion.TerminalValues)
			writeStringSliceField(output, "\t\t\t\t\t", "FailureValues", completion.FailureValues)
			fmt.Fprintln(output, "\t\t\t\t},")
			fmt.Fprintln(output, "\t\t\t},")
		}
	}
	if decision := generated.decisions.MCP; decision != nil && decision.State == "exposed" {
		group, _ := resolveMCP("", generated.id, operation, decision)
		fmt.Fprintln(output, "\t\t\tMCP: &MCPOperation{")
		fmt.Fprintf(output, "\t\t\t\tGroup: %q, Name: %q,\n", group, decision.Name)
		fmt.Fprintf(
			output,
			"\t\t\t\tReadOnly: %t, Destructive: %t, Idempotent: %t, OpenWorld: %t,\n",
			*decision.Annotations.ReadOnly,
			*decision.Annotations.Destructive,
			*decision.Annotations.Idempotent,
			*decision.Annotations.OpenWorld,
		)
		fmt.Fprintf(output, "\t\t\t\tInputSchema: json.RawMessage(%q),\n", generated.mcpInputSchema)
		fmt.Fprintln(output, "\t\t\t},")
	}
	fmt.Fprintln(output, "\t\t\tInput: InputDescriptor{")
	writeParameterDescriptors(output, "Path", generated.definition.PathParams)
	writeParameterDescriptors(output, "Query", generated.definition.QueryParams)
	writeBodyDescriptor(output, generated.definition)
	fmt.Fprintln(output, "\t\t\t},")
	fmt.Fprintf(output, "\t\t\tInvoke: invoke%s,\n", generated.definition.OperationId)
	fmt.Fprintln(output, "\t\t},")
}

func writeStringSliceField(output *bytes.Buffer, indent string, field string, values []string) {
	fmt.Fprintf(output, "%s%s: []string{", indent, field)
	for index, value := range values {
		if index > 0 {
			fmt.Fprint(output, ", ")
		}
		fmt.Fprintf(output, "%q", value)
	}
	fmt.Fprintln(output, "},")
}

func writeParameterDescriptors(output *bytes.Buffer, field string, parameters []codegen.ParameterDefinition) {
	if len(parameters) == 0 {
		return
	}
	fmt.Fprintf(output, "\t\t\t\t%s: []ParameterDescriptor{\n", field)
	for _, parameter := range parameters {
		schema := parameter.Schema.OAPISchema
		fmt.Fprintln(output, "\t\t\t\t\t{")
		fmt.Fprintf(output, "\t\t\t\t\t\tName: %q,\n", parameter.ParamName)
		fmt.Fprintf(output, "\t\t\t\t\t\tType: %q,\n", openAPIType(schema))
		fmt.Fprintf(output, "\t\t\t\t\t\tDescription: %q,\n", parameter.Spec.Description)
		fmt.Fprintf(output, "\t\t\t\t\t\tRequired: %t,\n", parameter.Required)
		if schema != nil && schema.Type.Is(openapi3.TypeArray) {
			fmt.Fprintln(output, "\t\t\t\t\t\tArray: true,")
			fmt.Fprintf(output, "\t\t\t\t\t\tItemType: %q,\n", openAPIType(schema.Items.Value))
		}
		writeEnum(output, "\t\t\t\t\t\t", descriptorEnum(schema))
		fmt.Fprintln(output, "\t\t\t\t\t},")
	}
	fmt.Fprintln(output, "\t\t\t\t},")
}

func writeBodyDescriptor(output *bytes.Buffer, operation codegen.OperationDefinition) {
	if !operation.HasBody() {
		return
	}
	schema := requestBodySchema(operation.Spec.RequestBody)
	fmt.Fprintln(output, "\t\t\t\tBody: BodyDescriptor{")
	fmt.Fprintln(output, "\t\t\t\t\tPresent: true,")
	fmt.Fprintf(output, "\t\t\t\t\tRequired: %t,\n", operation.BodyRequired)
	fmt.Fprintf(output, "\t\t\t\t\tType: %q,\n", openAPIType(schema))
	if schema != nil && schema.Type.Is(openapi3.TypeObject) {
		propertyNames := make([]string, 0, len(schema.Properties))
		for name := range schema.Properties {
			propertyNames = append(propertyNames, name)
		}
		sort.Strings(propertyNames)
		required := append([]string(nil), schema.Required...)
		sort.Strings(required)
		requiredSet := make(map[string]struct{}, len(required))
		for _, name := range required {
			requiredSet[name] = struct{}{}
		}
		if len(propertyNames) > 0 {
			fmt.Fprintln(output, "\t\t\t\t\tProperties: []BodyPropertyDescriptor{")
			for _, name := range propertyNames {
				property := schema.Properties[name].Value
				_, isRequired := requiredSet[name]
				fmt.Fprintln(output, "\t\t\t\t\t\t{")
				fmt.Fprintf(output, "\t\t\t\t\t\t\tName: %q,\n", name)
				fmt.Fprintf(output, "\t\t\t\t\t\t\tType: %q,\n", openAPIType(property))
				if property != nil {
					fmt.Fprintf(output, "\t\t\t\t\t\t\tDescription: %q,\n", property.Description)
				}
				fmt.Fprintf(output, "\t\t\t\t\t\t\tRequired: %t,\n", isRequired)
				if property != nil && property.Type.Is(openapi3.TypeArray) {
					fmt.Fprintln(output, "\t\t\t\t\t\t\tArray: true,")
					fmt.Fprintf(output, "\t\t\t\t\t\t\tItemType: %q,\n", openAPIType(property.Items.Value))
				}
				writeEnum(output, "\t\t\t\t\t\t\t", descriptorEnum(property))
				fmt.Fprintln(output, "\t\t\t\t\t\t},")
			}
			fmt.Fprintln(output, "\t\t\t\t\t},")
		}
		if len(required) > 0 {
			fmt.Fprint(output, "\t\t\t\t\tRequiredProperties: []string{")
			for _, name := range required {
				fmt.Fprintf(output, "%q,", name)
			}
			fmt.Fprintln(output, "},")
		}
	}
	fmt.Fprintf(output, "\t\t\t\t\tSimple: %t,\n", isSimpleBody(schema))
	fmt.Fprintln(output, "\t\t\t\t},")
}

func writeEnum(output *bytes.Buffer, indent string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(output, "%sEnum: []string{", indent)
	for _, value := range values {
		fmt.Fprintf(output, "%q,", value)
	}
	fmt.Fprintln(output, "},")
}

func requestBodySchema(requestBody *openapi3.RequestBodyRef) *openapi3.Schema {
	if requestBody == nil || requestBody.Value == nil {
		return nil
	}
	contentTypes := make([]string, 0, len(requestBody.Value.Content))
	for contentType := range requestBody.Value.Content {
		contentTypes = append(contentTypes, contentType)
	}
	sort.Strings(contentTypes)
	for _, contentType := range contentTypes {
		media := requestBody.Value.Content[contentType]
		if media != nil && media.Schema != nil {
			return media.Schema.Value
		}
	}
	return nil
}

func openAPIType(schema *openapi3.Schema) string {
	if schema == nil {
		return ""
	}
	typeName, _ := effectiveOpenAPIType(schema)
	return typeName
}

func descriptorEnum(schema *openapi3.Schema) []string {
	if schema == nil {
		return nil
	}
	if schema.Type.Is(openapi3.TypeArray) && schema.Items != nil {
		schema = schema.Items.Value
	}
	if schema == nil || len(schema.Enum) == 0 {
		return nil
	}
	values := make([]string, 0, len(schema.Enum))
	for _, value := range schema.Enum {
		if text, ok := value.(string); ok {
			values = append(values, text)
			continue
		}
		encoded, err := json.Marshal(value)
		if err != nil {
			continue
		}
		values = append(values, string(encoded))
	}
	return values
}

func isSimpleBody(schema *openapi3.Schema) bool {
	if schema == nil || !schema.Type.Is(openapi3.TypeObject) || schema.Nullable || hasComposition(schema) {
		return false
	}
	if schema.AdditionalProperties.Has == nil || *schema.AdditionalProperties.Has ||
		schema.AdditionalProperties.Schema != nil {
		return false
	}
	for _, property := range schema.Properties {
		if property == nil || !isSimpleBodyProperty(property.Value, true) {
			return false
		}
	}
	return true
}

func isSimpleBodyProperty(schema *openapi3.Schema, allowArray bool) bool {
	if schema == nil || schema.Nullable || hasComposition(schema) {
		return false
	}
	typeName, err := effectiveOpenAPIType(schema)
	if err != nil {
		return false
	}
	if typeName == openapi3.TypeString || typeName == openapi3.TypeInteger ||
		typeName == openapi3.TypeNumber || typeName == openapi3.TypeBoolean {
		return true
	}
	return allowArray && typeName == openapi3.TypeArray && schema.Items != nil &&
		isSimpleBodyProperty(schema.Items.Value, false)
}

func hasComposition(schema *openapi3.Schema) bool {
	return len(schema.AllOf) > 0 || len(schema.AnyOf) > 0 || len(schema.OneOf) > 0 || schema.Not != nil
}

func writeHelpers(output *bytes.Buffer) {
	fmt.Fprintln(output, `func validateInvocationInput(`)
	fmt.Fprintln(output, `	input InvocationInput,`)
	fmt.Fprintln(output, `	pathNames []string,`)
	fmt.Fprintln(output, `	queryNames []string,`)
	fmt.Fprintln(output, `	bodyPresent bool,`)
	fmt.Fprintln(output, `	bodyRequired bool,`)
	fmt.Fprintln(output, `) error {`)
	fmt.Fprintln(output, `	if len(input.Path) != len(pathNames) {`)
	fmt.Fprintln(output, `		return &InvocationInputError{`)
	fmt.Fprintln(output, `			Location: "path",`)
	fmt.Fprintln(output, `			Name: "values",`)
	fmt.Fprintf(output, "\t\t\tErr: fmt.Errorf(\"got %%d values, want %%d\", len(input.Path), len(pathNames)),\n")
	fmt.Fprintln(output, `		}`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	var unknownQueryNames []string`)
	fmt.Fprintln(output, `	for name := range input.Query {`)
	fmt.Fprintln(output, `		index := sort.SearchStrings(queryNames, name)`)
	fmt.Fprintln(output, `		if index == len(queryNames) || queryNames[index] != name {`)
	fmt.Fprintln(output, `			unknownQueryNames = append(unknownQueryNames, name)`)
	fmt.Fprintln(output, `		}`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	if len(unknownQueryNames) > 0 {`)
	fmt.Fprintln(output, `		sort.Strings(unknownQueryNames)`)
	fmt.Fprintln(output, `		return &InvocationInputError{`)
	fmt.Fprintln(output, `			Location: "query",`)
	fmt.Fprintln(output, `			Name: unknownQueryNames[0],`)
	fmt.Fprintln(output, `			Err: errors.New("parameter is not declared by the operation"),`)
	fmt.Fprintln(output, `		}`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	if !bodyPresent && input.Body != nil {`)
	fmt.Fprintln(output, `		return &InvocationInputError{`)
	fmt.Fprintln(output, `			Location: "body",`)
	fmt.Fprintln(output, `			Name: "body",`)
	fmt.Fprintln(output, `			Err: errors.New("operation does not accept a request body"),`)
	fmt.Fprintln(output, `		}`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	if bodyRequired && input.Body == nil {`)
	fmt.Fprintln(output, `		return &InvocationInputError{`)
	fmt.Fprintln(output, `			Location: "body",`)
	fmt.Fprintln(output, `			Name: "body",`)
	fmt.Fprintln(output, `			Err: errors.New("value is required"),`)
	fmt.Fprintln(output, `		}`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	return nil`)
	fmt.Fprintln(output, `}`)
	fmt.Fprintln(output)

	fmt.Fprintln(output, `func parseInvocationValue(raw string, stringValue bool, target any) error {`)
	fmt.Fprintln(output, `	encoded := []byte(raw)`)
	fmt.Fprintln(output, `	if stringValue {`)
	fmt.Fprintln(output, `		encoded, _ = json.Marshal(raw)`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	return json.Unmarshal(encoded, target)`)
	fmt.Fprintln(output, `}`)
	fmt.Fprintln(output)

	fmt.Fprintln(output, `func normalizeInvocationResult(body []byte, response *http.Response) (InvocationResult, error) {`)
	fmt.Fprintln(output, `	if response == nil {`)
	fmt.Fprintln(output, `		return InvocationResult{}, errors.New("generated client returned no HTTP response")`)
	fmt.Fprintln(output, `	}`)
	fmt.Fprintln(output, `	return InvocationResult{`)
	fmt.Fprintln(output, `		StatusCode: response.StatusCode,`)
	fmt.Fprintln(output, `		Headers: map[string][]string(response.Header.Clone()),`)
	fmt.Fprintln(output, `		Body: body,`)
	fmt.Fprintln(output, `	}, nil`)
	fmt.Fprintln(output, `}`)
	fmt.Fprintln(output)
}

func writeInvoker(output *bytes.Buffer, operation generatedOperation) {
	definition := operation.definition
	fmt.Fprintf(
		output,
		"func invoke%s(ctx context.Context, client ClientWithResponsesInterface, input InvocationInput) (InvocationResult, error) {\n",
		definition.OperationId,
	)
	pathNames := make([]string, 0, len(definition.PathParams))
	for _, parameter := range definition.PathParams {
		pathNames = append(pathNames, parameter.ParamName)
	}
	queryNames := make([]string, 0, len(definition.QueryParams))
	for _, parameter := range definition.QueryParams {
		queryNames = append(queryNames, parameter.ParamName)
	}
	sort.Strings(queryNames)
	fmt.Fprint(output, "\tif err := validateInvocationInput(input, ")
	writeStringSlice(output, pathNames)
	fmt.Fprint(output, ", ")
	writeStringSlice(output, queryNames)
	fmt.Fprintf(output, ", %t, %t); err != nil {\n", definition.HasBody(), definition.BodyRequired)
	fmt.Fprintln(output, "\t\treturn InvocationResult{}, err")
	fmt.Fprintln(output, "\t}")

	for index, parameter := range definition.PathParams {
		writePathConversion(output, index, parameter)
	}
	if len(definition.QueryParams) > 0 {
		fmt.Fprintf(output, "\tparams := &%sParams{}\n", definition.OperationId)
		for index, parameter := range definition.QueryParams {
			writeQueryConversion(output, index, parameter)
		}
	}

	fmt.Fprint(output, "\tresponse, err := client.")
	fmt.Fprint(output, definition.OperationId)
	if definition.HasBody() {
		fmt.Fprint(output, "WithBody")
	}
	fmt.Fprint(output, "WithResponse(ctx")
	for index := range definition.PathParams {
		fmt.Fprintf(output, ", pathValue%d", index)
	}
	if len(definition.QueryParams) > 0 {
		fmt.Fprint(output, ", params")
	}
	if definition.HasBody() {
		fmt.Fprint(output, `, "application/json", bytes.NewReader(input.Body)`)
	}
	fmt.Fprintln(output, ")")
	fmt.Fprintln(output, "\tif err != nil {")
	fmt.Fprintln(output, "\t\treturn InvocationResult{}, err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif response == nil {")
	fmt.Fprintln(output, "\t\treturn InvocationResult{}, errors.New(\"generated client returned no operation response\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn normalizeInvocationResult(response.Body, response.HTTPResponse)")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func writeStringSlice(output *bytes.Buffer, values []string) {
	if len(values) == 0 {
		fmt.Fprint(output, "nil")
		return
	}
	fmt.Fprint(output, "[]string{")
	for _, value := range values {
		fmt.Fprintf(output, "%q,", value)
	}
	fmt.Fprint(output, "}")
}

func writePathConversion(output *bytes.Buffer, index int, parameter codegen.ParameterDefinition) {
	fmt.Fprintf(output, "\tvar pathValue%d %s\n", index, parameter.TypeDef())
	fmt.Fprintf(
		output,
		"\tif err := parseInvocationValue(input.Path[%d], %t, &pathValue%d); err != nil {\n",
		index,
		isStringSchema(parameter.Schema.OAPISchema),
		index,
	)
	fmt.Fprintln(output, "\t\treturn InvocationResult{}, &InvocationInputError{")
	fmt.Fprintln(output, "\t\t\tLocation: \"path\",")
	fmt.Fprintf(output, "\t\t\tName: %q,\n", parameter.ParamName)
	fmt.Fprintf(output, "\t\t\tValue: input.Path[%d],\n", index)
	fmt.Fprintln(output, "\t\t\tErr: err,")
	fmt.Fprintln(output, "\t\t}")
	fmt.Fprintln(output, "\t}")
}

func writeQueryConversion(output *bytes.Buffer, index int, parameter codegen.ParameterDefinition) {
	valuesName := fmt.Sprintf("queryValues%d", index)
	suppliedName := fmt.Sprintf("querySupplied%d", index)
	fmt.Fprintf(output, "\t%s, %s := input.Query[%q]\n", valuesName, suppliedName, parameter.ParamName)
	if parameter.Required {
		fmt.Fprintf(output, "\tif !%s {\n", suppliedName)
		writeRequiredQueryError(output, parameter.ParamName)
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintf(output, "\tif %s {\n", suppliedName)
	schema := parameter.Schema.OAPISchema
	if schema != nil && schema.Type.Is(openapi3.TypeArray) {
		writeArrayQueryConversion(output, index, parameter, valuesName)
	} else {
		writeScalarQueryConversion(output, index, parameter, valuesName)
	}
	fmt.Fprintln(output, "\t}")
}

func writeRequiredQueryError(output *bytes.Buffer, name string) {
	fmt.Fprintln(output, "\t\treturn InvocationResult{}, &InvocationInputError{")
	fmt.Fprintln(output, "\t\t\tLocation: \"query\",")
	fmt.Fprintf(output, "\t\t\tName: %q,\n", name)
	fmt.Fprintln(output, "\t\t\tErr: errors.New(\"value is required\"),")
	fmt.Fprintln(output, "\t\t}")
}

func writeScalarQueryConversion(
	output *bytes.Buffer,
	index int,
	parameter codegen.ParameterDefinition,
	valuesName string,
) {
	fmt.Fprintf(output, "\t\tif len(%s) != 1 {\n", valuesName)
	fmt.Fprintln(output, "\t\t\treturn InvocationResult{}, &InvocationInputError{")
	fmt.Fprintln(output, "\t\t\t\tLocation: \"query\",")
	fmt.Fprintf(output, "\t\t\t\tName: %q,\n", parameter.ParamName)
	fmt.Fprintf(output, "\t\t\t\tErr: fmt.Errorf(\"got %%d values, want 1\", len(%s)),\n", valuesName)
	fmt.Fprintln(output, "\t\t\t}")
	fmt.Fprintln(output, "\t\t}")
	fmt.Fprintf(output, "\t\tvar queryValue%d %s\n", index, parameter.TypeDef())
	fmt.Fprintf(
		output,
		"\t\tif err := parseInvocationValue(%s[0], %t, &queryValue%d); err != nil {\n",
		valuesName,
		isStringSchema(parameter.Schema.OAPISchema),
		index,
	)
	writeQueryConversionError(output, parameter.ParamName, valuesName+"[0]", "\t\t\t")
	fmt.Fprintln(output, "\t\t}")
	writeQueryAssignment(output, parameter, fmt.Sprintf("queryValue%d", index))
}

func writeArrayQueryConversion(
	output *bytes.Buffer,
	index int,
	parameter codegen.ParameterDefinition,
	valuesName string,
) {
	fmt.Fprintf(output, "\t\tif len(%s) == 0 {\n", valuesName)
	writeRequiredQueryError(output, parameter.ParamName)
	fmt.Fprintln(output, "\t\t}")
	itemType := "any"
	if parameter.Schema.ArrayType != nil {
		itemType = parameter.Schema.ArrayType.TypeDecl()
	}
	fmt.Fprintf(output, "\t\tqueryValue%d := make([]%s, len(%s))\n", index, itemType, valuesName)
	fmt.Fprintf(output, "\t\tfor valueIndex, raw := range %s {\n", valuesName)
	itemSchema := (*openapi3.Schema)(nil)
	if parameter.Schema.OAPISchema != nil && parameter.Schema.OAPISchema.Items != nil {
		itemSchema = parameter.Schema.OAPISchema.Items.Value
	}
	fmt.Fprintf(
		output,
		"\t\t\tif err := parseInvocationValue(raw, %t, &queryValue%d[valueIndex]); err != nil {\n",
		isStringSchema(itemSchema),
		index,
	)
	writeQueryConversionError(output, parameter.ParamName, "raw", "\t\t\t\t")
	fmt.Fprintln(output, "\t\t\t}")
	fmt.Fprintln(output, "\t\t}")
	writeQueryAssignment(output, parameter, fmt.Sprintf("queryValue%d", index))
}

func writeQueryConversionError(output *bytes.Buffer, name string, value string, indent string) {
	fmt.Fprintf(output, "%sreturn InvocationResult{}, &InvocationInputError{\n", indent)
	fmt.Fprintf(output, "%s\tLocation: \"query\",\n", indent)
	fmt.Fprintf(output, "%s\tName: %q,\n", indent, name)
	fmt.Fprintf(output, "%s\tValue: %s,\n", indent, value)
	fmt.Fprintf(output, "%s\tErr: err,\n", indent)
	fmt.Fprintf(output, "%s}\n", indent)
}

func writeQueryAssignment(
	output *bytes.Buffer,
	parameter codegen.ParameterDefinition,
	valueName string,
) {
	if parameter.HasOptionalPointer() {
		fmt.Fprintf(output, "\t\tparams.%s = &%s\n", parameter.GoName(), valueName)
		return
	}
	fmt.Fprintf(output, "\t\tparams.%s = %s\n", parameter.GoName(), valueName)
}

func isStringSchema(schema *openapi3.Schema) bool {
	if schema == nil {
		return false
	}
	typeName, err := effectiveOpenAPIType(schema)
	return err == nil && typeName == openapi3.TypeString
}
