name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  docker-image:
    name: Docker image
    needs: tests
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-image.yml
    with:
      promote-main: ${{ github.ref == 'refs/heads/main' }}
